# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VectorFieldRendererWidget.ui'
#
# Created: Mon Jan 14 17:14:06 2013
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_VectorFieldRendererWidget(object):
    def setupUi(self, VectorFieldRendererWidget):
        VectorFieldRendererWidget.setObjectName(_fromUtf8("VectorFieldRendererWidget"))
        VectorFieldRendererWidget.resize(664, 477)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VectorFieldRendererWidget.sizePolicy().hasHeightForWidth())
        VectorFieldRendererWidget.setSizePolicy(sizePolicy)
        VectorFieldRendererWidget.setWindowTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_4 = QtGui.QVBoxLayout(VectorFieldRendererWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.uTabManager = QtGui.QTabWidget(VectorFieldRendererWidget)
        self.uTabManager.setObjectName(_fromUtf8("uTabManager"))
        self.uVectorTab = QtGui.QWidget()
        self.uVectorTab.setObjectName(_fromUtf8("uVectorTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.uVectorTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uVectorFieldTypeGroupBox = QtGui.QGroupBox(self.uVectorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uVectorFieldTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uVectorFieldTypeGroupBox.setSizePolicy(sizePolicy)
        self.uVectorFieldTypeGroupBox.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Vector field type", None, QtGui.QApplication.UnicodeUTF8))
        self.uVectorFieldTypeGroupBox.setObjectName(_fromUtf8("uVectorFieldTypeGroupBox"))
        self.uFieldTypeLayout = QtGui.QHBoxLayout(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeLayout.setMargin(0)
        self.uFieldTypeLayout.setObjectName(_fromUtf8("uFieldTypeLayout"))
        self.uFieldTypeCartesian = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeCartesian.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Cartesian (XY) field", None, QtGui.QApplication.UnicodeUTF8))
        self.uFieldTypeCartesian.setChecked(True)
        self.uFieldTypeCartesian.setObjectName(_fromUtf8("uFieldTypeCartesian"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypeCartesian)
        self.uFieldTypePolar = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypePolar.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Polar (length,angle) field", None, QtGui.QApplication.UnicodeUTF8))
        self.uFieldTypePolar.setObjectName(_fromUtf8("uFieldTypePolar"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypePolar)
        self.uFieldTypeHeight = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeHeight.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Height only", None, QtGui.QApplication.UnicodeUTF8))
        self.uFieldTypeHeight.setObjectName(_fromUtf8("uFieldTypeHeight"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypeHeight)
        self.uFieldTypeNone = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeNone.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.uFieldTypeNone.setObjectName(_fromUtf8("uFieldTypeNone"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypeNone)
        self.verticalLayout.addWidget(self.uVectorFieldTypeGroupBox)
        self.uVectorFieldGrid = QtGui.QGridLayout()
        self.uVectorFieldGrid.setObjectName(_fromUtf8("uVectorFieldGrid"))
        self.uXFieldLabel = QtGui.QLabel(self.uVectorTab)
        self.uXFieldLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "X attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.uXFieldLabel.setObjectName(_fromUtf8("uXFieldLabel"))
        self.uVectorFieldGrid.addWidget(self.uXFieldLabel, 0, 0, 1, 1)
        self.uXField = QtGui.QComboBox(self.uVectorTab)
        self.uXField.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the X/length field", None, QtGui.QApplication.UnicodeUTF8))
        self.uXField.setObjectName(_fromUtf8("uXField"))
        self.uVectorFieldGrid.addWidget(self.uXField, 0, 2, 1, 1)
        self.uYFieldLabel = QtGui.QLabel(self.uVectorTab)
        self.uYFieldLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Y attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.uYFieldLabel.setObjectName(_fromUtf8("uYFieldLabel"))
        self.uVectorFieldGrid.addWidget(self.uYFieldLabel, 1, 0, 1, 1)
        self.uYField = QtGui.QComboBox(self.uVectorTab)
        self.uYField.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the y/angle field", None, QtGui.QApplication.UnicodeUTF8))
        self.uYField.setObjectName(_fromUtf8("uYField"))
        self.uVectorFieldGrid.addWidget(self.uYField, 1, 2, 1, 1)
        self.uArrowScaleLabel = QtGui.QLabel(self.uVectorTab)
        self.uArrowScaleLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Scale:  ", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowScaleLabel.setObjectName(_fromUtf8("uArrowScaleLabel"))
        self.uVectorFieldGrid.addWidget(self.uArrowScaleLabel, 2, 0, 1, 1)
        self.uArrowScaleLayout = QtGui.QHBoxLayout()
        self.uArrowScaleLayout.setObjectName(_fromUtf8("uArrowScaleLayout"))
        self.uArrowScale = QtGui.QLineEdit(self.uVectorTab)
        self.uArrowScale.setObjectName(_fromUtf8("uArrowScale"))
        self.uArrowScaleLayout.addWidget(self.uArrowScale)
        self.uScaleUnits = QtGui.QPushButton(self.uVectorTab)
        self.uScaleUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uScaleUnits.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Millimeter", None, QtGui.QApplication.UnicodeUTF8))
        self.uScaleUnits.setObjectName(_fromUtf8("uScaleUnits"))
        self.uArrowScaleLayout.addWidget(self.uScaleUnits)
        self.uScaleGroupLabel = QtGui.QLabel(self.uVectorTab)
        self.uScaleGroupLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "    Scale group", None, QtGui.QApplication.UnicodeUTF8))
        self.uScaleGroupLabel.setObjectName(_fromUtf8("uScaleGroupLabel"))
        self.uArrowScaleLayout.addWidget(self.uScaleGroupLabel)
        self.uScaleGroup = QtGui.QLineEdit(self.uVectorTab)
        self.uScaleGroup.setObjectName(_fromUtf8("uScaleGroup"))
        self.uArrowScaleLayout.addWidget(self.uScaleGroup)
        self.uVectorFieldGrid.addLayout(self.uArrowScaleLayout, 2, 2, 1, 1)
        self.verticalLayout.addLayout(self.uVectorFieldGrid)
        self.uAngleFormatLayout = QtGui.QHBoxLayout()
        self.uAngleFormatLayout.setContentsMargins(0, -1, 0, -1)
        self.uAngleFormatLayout.setObjectName(_fromUtf8("uAngleFormatLayout"))
        self.uOrientationGroupBox = QtGui.QGroupBox(self.uVectorTab)
        self.uOrientationGroupBox.setEnabled(False)
        self.uOrientationGroupBox.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Angle orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.uOrientationGroupBox.setObjectName(_fromUtf8("uOrientationGroupBox"))
        self.uOrientationLayout = QtGui.QHBoxLayout(self.uOrientationGroupBox)
        self.uOrientationLayout.setSpacing(6)
        self.uOrientationLayout.setMargin(9)
        self.uOrientationLayout.setObjectName(_fromUtf8("uOrientationLayout"))
        self.uAngleOrientationEast = QtGui.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationEast.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleOrientationEast.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "North from east", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleOrientationEast.setChecked(True)
        self.uAngleOrientationEast.setObjectName(_fromUtf8("uAngleOrientationEast"))
        self.uOrientationLayout.addWidget(self.uAngleOrientationEast)
        self.uAngleOrientationNorth = QtGui.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationNorth.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleOrientationNorth.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "East from north", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleOrientationNorth.setObjectName(_fromUtf8("uAngleOrientationNorth"))
        self.uOrientationLayout.addWidget(self.uAngleOrientationNorth)
        self.uAngleFormatLayout.addWidget(self.uOrientationGroupBox)
        self.uAngleUnitsGroupBox = QtGui.QGroupBox(self.uVectorTab)
        self.uAngleUnitsGroupBox.setEnabled(False)
        self.uAngleUnitsGroupBox.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Angle units", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleUnitsGroupBox.setObjectName(_fromUtf8("uAngleUnitsGroupBox"))
        self.uAngleUnitsLayout = QtGui.QHBoxLayout(self.uAngleUnitsGroupBox)
        self.uAngleUnitsLayout.setContentsMargins(-1, 9, -1, 9)
        self.uAngleUnitsLayout.setObjectName(_fromUtf8("uAngleUnitsLayout"))
        self.uAngleUnitsDegrees = QtGui.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsDegrees.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle units", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleUnitsDegrees.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleUnitsDegrees.setChecked(True)
        self.uAngleUnitsDegrees.setObjectName(_fromUtf8("uAngleUnitsDegrees"))
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsDegrees)
        self.uAngleUnitsRadians = QtGui.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsRadians.setEnabled(False)
        self.uAngleUnitsRadians.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle units", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleUnitsRadians.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Radians", None, QtGui.QApplication.UnicodeUTF8))
        self.uAngleUnitsRadians.setObjectName(_fromUtf8("uAngleUnitsRadians"))
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsRadians)
        self.uAngleFormatLayout.addWidget(self.uAngleUnitsGroupBox)
        self.verticalLayout.addLayout(self.uAngleFormatLayout)
        self.uArrowFormatGroup = QtGui.QGroupBox(self.uVectorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowFormatGroup.sizePolicy().hasHeightForWidth())
        self.uArrowFormatGroup.setSizePolicy(sizePolicy)
        self.uArrowFormatGroup.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Arrow format", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowFormatGroup.setObjectName(_fromUtf8("uArrowFormatGroup"))
        self.uArrowFormatLayout = QtGui.QVBoxLayout(self.uArrowFormatGroup)
        self.uArrowFormatLayout.setMargin(0)
        self.uArrowFormatLayout.setObjectName(_fromUtf8("uArrowFormatLayout"))
        self.uArrowSizeLayout = QtGui.QHBoxLayout()
        self.uArrowSizeLayout.setObjectName(_fromUtf8("uArrowSizeLayout"))
        self.uArrowSizeLayoutLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowSizeLayoutLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowSizeLayoutLabel.setObjectName(_fromUtf8("uArrowSizeLayoutLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowSizeLayoutLabel)
        self.uArrowHeadSizeLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadSizeLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Head (relative)", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowHeadSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadSizeLabel.setObjectName(_fromUtf8("uArrowHeadSizeLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSizeLabel)
        self.uArrowHeadSize = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadSize.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowHeadSize.setSingleStep(0.1)
        self.uArrowHeadSize.setObjectName(_fromUtf8("uArrowHeadSize"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadMaxSizeLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Head (maximum)", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowHeadMaxSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadMaxSizeLabel.setObjectName(_fromUtf8("uArrowHeadMaxSizeLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSizeLabel)
        self.uArrowHeadMaxSize = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadMaxSize.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Maximum arrow head size", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowHeadMaxSize.setObjectName(_fromUtf8("uArrowHeadMaxSize"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSize)
        self.uArrowWidthLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowWidthLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Width", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowWidthLabel.setObjectName(_fromUtf8("uArrowWidthLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowWidthLabel)
        self.uArrowWidth = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowWidth.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Width of the arrow shaft", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowWidth.setObjectName(_fromUtf8("uArrowWidth"))
        self.uArrowSizeLayout.addWidget(self.uArrowWidth)
        self.uArrowFormatLayout.addLayout(self.uArrowSizeLayout)
        self.uArrowColorLayout = QtGui.QHBoxLayout()
        self.uArrowColorLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.uArrowColorLayout.setContentsMargins(-1, 0, -1, -1)
        self.uArrowColorLayout.setObjectName(_fromUtf8("uArrowColorLayout"))
        self.uArrowColorLabel = QtGui.QLabel(self.uArrowFormatGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowColorLabel.sizePolicy().hasHeightForWidth())
        self.uArrowColorLabel.setSizePolicy(sizePolicy)
        self.uArrowColorLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Arrow colour:", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowColorLabel.setObjectName(_fromUtf8("uArrowColorLabel"))
        self.uArrowColorLayout.addWidget(self.uArrowColorLabel)
        self.uArrowColor = QgsColorButtonV2(self.uArrowFormatGroup)
        self.uArrowColor.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Change the arrow colour", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowColor.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowColor.setObjectName(_fromUtf8("uArrowColor"))
        self.uArrowColorLayout.addWidget(self.uArrowColor)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowColorLayout.addItem(spacerItem)
        self.uArrowFormatLayout.addLayout(self.uArrowColorLayout)
        self.verticalLayout.addWidget(self.uArrowFormatGroup)
        self.uTabManager.addTab(self.uVectorTab, _fromUtf8(""))
        self.uEllipseTab = QtGui.QWidget()
        self.uEllipseTab.setObjectName(_fromUtf8("uEllipseTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uEllipseTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.uErrorEllipseTypeGroupBox = QtGui.QGroupBox(self.uEllipseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uErrorEllipseTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uErrorEllipseTypeGroupBox.setSizePolicy(sizePolicy)
        self.uErrorEllipseTypeGroupBox.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Error ellipse type", None, QtGui.QApplication.UnicodeUTF8))
        self.uErrorEllipseTypeGroupBox.setObjectName(_fromUtf8("uErrorEllipseTypeGroupBox"))
        self.uFieldTypeLayout_2 = QtGui.QHBoxLayout(self.uErrorEllipseTypeGroupBox)
        self.uFieldTypeLayout_2.setMargin(0)
        self.uFieldTypeLayout_2.setObjectName(_fromUtf8("uFieldTypeLayout_2"))
        self.uEllipseTypeCovariance = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCovariance.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Covariance matrix", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseTypeCovariance.setChecked(False)
        self.uEllipseTypeCovariance.setObjectName(_fromUtf8("uEllipseTypeCovariance"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCovariance)
        self.uEllipseTypeAxes = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeAxes.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Ellipses axes", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseTypeAxes.setObjectName(_fromUtf8("uEllipseTypeAxes"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeAxes)
        self.uEllipseTypeCircular = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCircular.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseTypeCircular.setObjectName(_fromUtf8("uEllipseTypeCircular"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCircular)
        self.uEllipseTypeHeight = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeHeight.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Height", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseTypeHeight.setObjectName(_fromUtf8("uEllipseTypeHeight"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeHeight)
        self.uEllipseTypeNone = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeNone.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseTypeNone.setChecked(True)
        self.uEllipseTypeNone.setObjectName(_fromUtf8("uEllipseTypeNone"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeNone)
        self.verticalLayout_2.addWidget(self.uErrorEllipseTypeGroupBox)
        self.uVectorFieldGrid_2 = QtGui.QGridLayout()
        self.uVectorFieldGrid_2.setObjectName(_fromUtf8("uVectorFieldGrid_2"))
        self.uCxxFieldLabel = QtGui.QLabel(self.uEllipseTab)
        self.uCxxFieldLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Cxx attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.uCxxFieldLabel.setObjectName(_fromUtf8("uCxxFieldLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uCxxFieldLabel, 0, 0, 1, 1)
        self.uCxyFieldLabel = QtGui.QLabel(self.uEllipseTab)
        self.uCxyFieldLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Cxy attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.uCxyFieldLabel.setObjectName(_fromUtf8("uCxyFieldLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uCxyFieldLabel, 1, 0, 1, 1)
        self.uCxyField = QtGui.QComboBox(self.uEllipseTab)
        self.uCxyField.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the y/angle field", None, QtGui.QApplication.UnicodeUTF8))
        self.uCxyField.setObjectName(_fromUtf8("uCxyField"))
        self.uVectorFieldGrid_2.addWidget(self.uCxyField, 1, 2, 1, 1)
        self.uEllipseScaleLabel = QtGui.QLabel(self.uEllipseTab)
        self.uEllipseScaleLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Relative scale", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseScaleLabel.setObjectName(_fromUtf8("uEllipseScaleLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uEllipseScaleLabel, 3, 0, 1, 1)
        self.uArrowScaleLayout_2 = QtGui.QHBoxLayout()
        self.uArrowScaleLayout_2.setObjectName(_fromUtf8("uArrowScaleLayout_2"))
        self.uEllipseScale = QtGui.QLineEdit(self.uEllipseTab)
        self.uEllipseScale.setObjectName(_fromUtf8("uEllipseScale"))
        self.uArrowScaleLayout_2.addWidget(self.uEllipseScale)
        self.uEllipseScaleLabel2 = QtGui.QLabel(self.uEllipseTab)
        self.uEllipseScaleLabel2.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "(ie relative to arrow scale)", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseScaleLabel2.setObjectName(_fromUtf8("uEllipseScaleLabel2"))
        self.uArrowScaleLayout_2.addWidget(self.uEllipseScaleLabel2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowScaleLayout_2.addItem(spacerItem1)
        self.uVectorFieldGrid_2.addLayout(self.uArrowScaleLayout_2, 3, 2, 1, 1)
        self.uCxxField = QtGui.QComboBox(self.uEllipseTab)
        self.uCxxField.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the X/length field", None, QtGui.QApplication.UnicodeUTF8))
        self.uCxxField.setObjectName(_fromUtf8("uCxxField"))
        self.uVectorFieldGrid_2.addWidget(self.uCxxField, 0, 2, 1, 1)
        self.uCyyFieldLabel = QtGui.QLabel(self.uEllipseTab)
        self.uCyyFieldLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Cyy attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.uCyyFieldLabel.setObjectName(_fromUtf8("uCyyFieldLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uCyyFieldLabel, 2, 0, 1, 1)
        self.uCyyField = QtGui.QComboBox(self.uEllipseTab)
        self.uCyyField.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the y/angle field", None, QtGui.QApplication.UnicodeUTF8))
        self.uCyyField.setObjectName(_fromUtf8("uCyyField"))
        self.uVectorFieldGrid_2.addWidget(self.uCyyField, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.uVectorFieldGrid_2)
        self.uAxisAngleFormatLayout = QtGui.QHBoxLayout()
        self.uAxisAngleFormatLayout.setContentsMargins(-1, 0, -1, -1)
        self.uAxisAngleFormatLayout.setObjectName(_fromUtf8("uAxisAngleFormatLayout"))
        self.uAxisOrientationGroupBox = QtGui.QGroupBox(self.uEllipseTab)
        self.uAxisOrientationGroupBox.setEnabled(False)
        self.uAxisOrientationGroupBox.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Ellipse axis orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.uAxisOrientationGroupBox.setObjectName(_fromUtf8("uAxisOrientationGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.uAxisOrientationGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uEllipseOrientationEast = QtGui.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationEast.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseOrientationEast.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "North from east", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseOrientationEast.setChecked(True)
        self.uEllipseOrientationEast.setObjectName(_fromUtf8("uEllipseOrientationEast"))
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationEast)
        self.uEllipseOrientationNorth = QtGui.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationNorth.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseOrientationNorth.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "East from north", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseOrientationNorth.setObjectName(_fromUtf8("uEllipseOrientationNorth"))
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationNorth)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisOrientationGroupBox)
        self.uAxisAngleUnitsGroupBox = QtGui.QGroupBox(self.uEllipseTab)
        self.uAxisAngleUnitsGroupBox.setEnabled(False)
        self.uAxisAngleUnitsGroupBox.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Angle units", None, QtGui.QApplication.UnicodeUTF8))
        self.uAxisAngleUnitsGroupBox.setObjectName(_fromUtf8("uAxisAngleUnitsGroupBox"))
        self.uAngleUnitsLayout_2 = QtGui.QHBoxLayout(self.uAxisAngleUnitsGroupBox)
        self.uAngleUnitsLayout_2.setContentsMargins(-1, 9, -1, 9)
        self.uAngleUnitsLayout_2.setObjectName(_fromUtf8("uAngleUnitsLayout_2"))
        self.uEllipseAngleUnitsDegrees = QtGui.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsDegrees.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle units", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseAngleUnitsDegrees.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseAngleUnitsDegrees.setChecked(True)
        self.uEllipseAngleUnitsDegrees.setObjectName(_fromUtf8("uEllipseAngleUnitsDegrees"))
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsDegrees)
        self.uEllipseAngleUnitsRadians = QtGui.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsRadians.setEnabled(False)
        self.uEllipseAngleUnitsRadians.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Select the angle units", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseAngleUnitsRadians.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Radians", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseAngleUnitsRadians.setObjectName(_fromUtf8("uEllipseAngleUnitsRadians"))
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsRadians)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisAngleUnitsGroupBox)
        self.verticalLayout_2.addLayout(self.uAxisAngleFormatLayout)
        self.uEllipseFormatGroup = QtGui.QGroupBox(self.uEllipseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uEllipseFormatGroup.sizePolicy().hasHeightForWidth())
        self.uEllipseFormatGroup.setSizePolicy(sizePolicy)
        self.uEllipseFormatGroup.setTitle(QtGui.QApplication.translate("VectorFieldRendererWidget", "Ellipse format", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseFormatGroup.setObjectName(_fromUtf8("uEllipseFormatGroup"))
        self.uArrowFormatLayout_2 = QtGui.QVBoxLayout(self.uEllipseFormatGroup)
        self.uArrowFormatLayout_2.setMargin(0)
        self.uArrowFormatLayout_2.setObjectName(_fromUtf8("uArrowFormatLayout_2"))
        self.uArrowUnitsLayout_2 = QtGui.QHBoxLayout()
        self.uArrowUnitsLayout_2.setObjectName(_fromUtf8("uArrowUnitsLayout_2"))
        self.uEllipseWidthLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uEllipseWidthLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Border width", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uEllipseWidthLabel.setObjectName(_fromUtf8("uEllipseWidthLabel"))
        self.uArrowUnitsLayout_2.addWidget(self.uEllipseWidthLabel)
        self.uEllipseBorderWidth = QtGui.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseBorderWidth.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Width of the arrow shaft", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseBorderWidth.setObjectName(_fromUtf8("uEllipseBorderWidth"))
        self.uArrowUnitsLayout_2.addWidget(self.uEllipseBorderWidth)
        self.label = QtGui.QLabel(self.uEllipseFormatGroup)
        self.label.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Fill ellipse: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.uArrowUnitsLayout_2.addWidget(self.label)
        self.uFillEllipse = QtGui.QCheckBox(self.uEllipseFormatGroup)
        self.uFillEllipse.setText(_fromUtf8(""))
        self.uFillEllipse.setObjectName(_fromUtf8("uFillEllipse"))
        self.uArrowUnitsLayout_2.addWidget(self.uFillEllipse)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowUnitsLayout_2.addItem(spacerItem2)
        self.uArrowFormatLayout_2.addLayout(self.uArrowUnitsLayout_2)
        self.uEllipseArrowColorLayout = QtGui.QHBoxLayout()
        self.uEllipseArrowColorLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.uEllipseArrowColorLayout.setContentsMargins(-1, 0, -1, -1)
        self.uEllipseArrowColorLayout.setObjectName(_fromUtf8("uEllipseArrowColorLayout"))
        self.uEllipseColorLayoutLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uEllipseColorLayoutLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Ellipse olours:", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseColorLayoutLabel.setObjectName(_fromUtf8("uEllipseColorLayoutLabel"))
        self.uEllipseArrowColorLayout.addWidget(self.uEllipseColorLayoutLabel)
        self.uEllipseBorderColorLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uEllipseBorderColorLabel.sizePolicy().hasHeightForWidth())
        self.uEllipseBorderColorLabel.setSizePolicy(sizePolicy)
        self.uEllipseBorderColorLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Border", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseBorderColorLabel.setObjectName(_fromUtf8("uEllipseBorderColorLabel"))
        self.uEllipseArrowColorLayout.addWidget(self.uEllipseBorderColorLabel)
        self.uEllipseBorderColor = QgsColorButtonV2(self.uEllipseFormatGroup)
        self.uEllipseBorderColor.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Change the arrow colour", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseBorderColor.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseBorderColor.setObjectName(_fromUtf8("uEllipseBorderColor"))
        self.uEllipseArrowColorLayout.addWidget(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uEllipseFillColorLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Fill", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseFillColorLabel.setObjectName(_fromUtf8("uEllipseFillColorLabel"))
        self.uEllipseArrowColorLayout.addWidget(self.uEllipseFillColorLabel)
        self.uEllipseFillColor = QgsColorButtonV2(self.uEllipseFormatGroup)
        self.uEllipseFillColor.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Change the base symbol colour", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseFillColor.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.uEllipseFillColor.setObjectName(_fromUtf8("uEllipseFillColor"))
        self.uEllipseArrowColorLayout.addWidget(self.uEllipseFillColor)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uEllipseArrowColorLayout.addItem(spacerItem3)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseArrowColorLayout)
        self.verticalLayout_2.addWidget(self.uEllipseFormatGroup)
        self.uTabManager.addTab(self.uEllipseTab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.uTabManager)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uOutputUnitLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uOutputUnitLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Symbol units:", None, QtGui.QApplication.UnicodeUTF8))
        self.uOutputUnitLabel.setObjectName(_fromUtf8("uOutputUnitLabel"))
        self.horizontalLayout_3.addWidget(self.uOutputUnitLabel)
        self.uOutputUnits = QtGui.QPushButton(VectorFieldRendererWidget)
        self.uOutputUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uOutputUnits.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Millimeter", None, QtGui.QApplication.UnicodeUTF8))
        self.uOutputUnits.setObjectName(_fromUtf8("uOutputUnits"))
        self.horizontalLayout_3.addWidget(self.uOutputUnits)
        self.uArrowBaseSizeLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uArrowBaseSizeLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Base size:", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowBaseSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowBaseSizeLabel.setObjectName(_fromUtf8("uArrowBaseSizeLabel"))
        self.horizontalLayout_3.addWidget(self.uArrowBaseSizeLabel)
        self.uArrowBaseSize = QtGui.QDoubleSpinBox(VectorFieldRendererWidget)
        self.uArrowBaseSize.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Size of the arrow base symbol", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowBaseSize.setObjectName(_fromUtf8("uArrowBaseSize"))
        self.horizontalLayout_3.addWidget(self.uArrowBaseSize)
        self.uBaseColorLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uBaseColorLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Base fill:", None, QtGui.QApplication.UnicodeUTF8))
        self.uBaseColorLabel.setObjectName(_fromUtf8("uBaseColorLabel"))
        self.horizontalLayout_3.addWidget(self.uBaseColorLabel)
        self.uBaseColor = QgsColorButtonV2(VectorFieldRendererWidget)
        self.uBaseColor.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Change the base symbol colour", None, QtGui.QApplication.UnicodeUTF8))
        self.uBaseColor.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.uBaseColor.setObjectName(_fromUtf8("uBaseColor"))
        self.horizontalLayout_3.addWidget(self.uBaseColor)
        self.uBaseBorderColorLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uBaseBorderColorLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Base border:", None, QtGui.QApplication.UnicodeUTF8))
        self.uBaseBorderColorLabel.setObjectName(_fromUtf8("uBaseBorderColorLabel"))
        self.horizontalLayout_3.addWidget(self.uBaseBorderColorLabel)
        self.uBaseBorderColor = QgsColorButtonV2(VectorFieldRendererWidget)
        self.uBaseBorderColor.setToolTip(QtGui.QApplication.translate("VectorFieldRendererWidget", "Change the base border colour", None, QtGui.QApplication.UnicodeUTF8))
        self.uBaseBorderColor.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "change", None, QtGui.QApplication.UnicodeUTF8))
        self.uBaseBorderColor.setObjectName(_fromUtf8("uBaseBorderColor"))
        self.horizontalLayout_3.addWidget(self.uBaseBorderColor)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uLegendTextLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uLegendTextLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Legend text: ", None, QtGui.QApplication.UnicodeUTF8))
        self.uLegendTextLabel.setObjectName(_fromUtf8("uLegendTextLabel"))
        self.horizontalLayout.addWidget(self.uLegendTextLabel)
        self.uLegendText = QtGui.QLineEdit(VectorFieldRendererWidget)
        self.uLegendText.setObjectName(_fromUtf8("uLegendText"))
        self.horizontalLayout.addWidget(self.uLegendText)
        self.uScaleBoxTextLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uScaleBoxTextLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Scale box text: ", None, QtGui.QApplication.UnicodeUTF8))
        self.uScaleBoxTextLabel.setObjectName(_fromUtf8("uScaleBoxTextLabel"))
        self.horizontalLayout.addWidget(self.uScaleBoxTextLabel)
        self.uScaleBoxText = QtGui.QLineEdit(VectorFieldRendererWidget)
        self.uScaleBoxText.setObjectName(_fromUtf8("uScaleBoxText"))
        self.horizontalLayout.addWidget(self.uScaleBoxText)
        self.uShowScaleBoxLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uShowScaleBoxLabel.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Show?", None, QtGui.QApplication.UnicodeUTF8))
        self.uShowScaleBoxLabel.setObjectName(_fromUtf8("uShowScaleBoxLabel"))
        self.horizontalLayout.addWidget(self.uShowScaleBoxLabel)
        self.uShowInScaleBox = QtGui.QCheckBox(VectorFieldRendererWidget)
        self.uShowInScaleBox.setText(_fromUtf8(""))
        self.uShowInScaleBox.setObjectName(_fromUtf8("uShowInScaleBox"))
        self.horizontalLayout.addWidget(self.uShowInScaleBox)
        self.uHelpButton = QtGui.QPushButton(VectorFieldRendererWidget)
        self.uHelpButton.setText(QtGui.QApplication.translate("VectorFieldRendererWidget", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.uHelpButton.setObjectName(_fromUtf8("uHelpButton"))
        self.horizontalLayout.addWidget(self.uHelpButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.uXFieldLabel.setBuddy(self.uXField)
        self.uYFieldLabel.setBuddy(self.uYField)
        self.uArrowScaleLabel.setBuddy(self.uArrowScale)
        self.uScaleGroupLabel.setBuddy(self.uScaleGroup)
        self.uArrowSizeLayoutLabel.setBuddy(self.uArrowHeadSize)
        self.uArrowHeadSizeLabel.setBuddy(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel.setBuddy(self.uArrowHeadMaxSize)
        self.uArrowWidthLabel.setBuddy(self.uArrowWidth)
        self.uArrowColorLabel.setBuddy(self.uArrowColor)
        self.uCxxFieldLabel.setBuddy(self.uXField)
        self.uCxyFieldLabel.setBuddy(self.uYField)
        self.uEllipseScaleLabel.setBuddy(self.uArrowScale)
        self.uCyyFieldLabel.setBuddy(self.uYField)
        self.uEllipseWidthLabel.setBuddy(self.uArrowWidth)
        self.uEllipseColorLayoutLabel.setBuddy(self.uArrowColor)
        self.uEllipseBorderColorLabel.setBuddy(self.uArrowColor)
        self.uEllipseFillColorLabel.setBuddy(self.uBaseColor)
        self.uOutputUnitLabel.setBuddy(self.uOutputUnits)
        self.uArrowBaseSizeLabel.setBuddy(self.uArrowBaseSize)
        self.uBaseColorLabel.setBuddy(self.uBaseColor)
        self.uBaseBorderColorLabel.setBuddy(self.uBaseBorderColor)
        self.uLegendTextLabel.setBuddy(self.uLegendText)
        self.uScaleBoxTextLabel.setBuddy(self.uScaleBoxText)
        self.uShowScaleBoxLabel.setBuddy(self.uShowInScaleBox)

        self.retranslateUi(VectorFieldRendererWidget)
        self.uTabManager.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(VectorFieldRendererWidget)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeCartesian, self.uFieldTypePolar)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypePolar, self.uXField)
        VectorFieldRendererWidget.setTabOrder(self.uXField, self.uYField)
        VectorFieldRendererWidget.setTabOrder(self.uYField, self.uArrowScale)
        VectorFieldRendererWidget.setTabOrder(self.uArrowScale, self.uScaleUnits)
        VectorFieldRendererWidget.setTabOrder(self.uScaleUnits, self.uScaleGroup)
        VectorFieldRendererWidget.setTabOrder(self.uScaleGroup, self.uAngleOrientationEast)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationEast, self.uAngleOrientationNorth)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationNorth, self.uAngleUnitsDegrees)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsDegrees, self.uAngleUnitsRadians)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsRadians, self.uArrowHeadSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadSize, self.uArrowHeadMaxSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadMaxSize, self.uArrowWidth)
        VectorFieldRendererWidget.setTabOrder(self.uArrowWidth, self.uArrowColor)

    def retranslateUi(self, VectorFieldRendererWidget):
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uVectorTab), QtGui.QApplication.translate("VectorFieldRendererWidget", "Vector field", None, QtGui.QApplication.UnicodeUTF8))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uEllipseTab), QtGui.QApplication.translate("VectorFieldRendererWidget", "Error ellipse", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsColorButtonV2
