# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VectorFieldRendererWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VectorFieldRendererWidget(object):
    def setupUi(self, VectorFieldRendererWidget):
        VectorFieldRendererWidget.setObjectName("VectorFieldRendererWidget")
        VectorFieldRendererWidget.resize(791, 532)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VectorFieldRendererWidget.sizePolicy().hasHeightForWidth())
        VectorFieldRendererWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(VectorFieldRendererWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.uTabManager = QtWidgets.QTabWidget(VectorFieldRendererWidget)
        self.uTabManager.setObjectName("uTabManager")
        self.uVectorTab = QtWidgets.QWidget()
        self.uVectorTab.setObjectName("uVectorTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.uVectorTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uVectorFieldTypeGroupBox = QtWidgets.QGroupBox(self.uVectorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uVectorFieldTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uVectorFieldTypeGroupBox.setSizePolicy(sizePolicy)
        self.uVectorFieldTypeGroupBox.setObjectName("uVectorFieldTypeGroupBox")
        self.uFieldTypeLayout = QtWidgets.QHBoxLayout(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeLayout.setContentsMargins(0, 0, 0, 0)
        self.uFieldTypeLayout.setSpacing(15)
        self.uFieldTypeLayout.setObjectName("uFieldTypeLayout")
        self.uFieldTypeCartesian = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeCartesian.setChecked(True)
        self.uFieldTypeCartesian.setObjectName("uFieldTypeCartesian")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeCartesian)
        self.uFieldTypePolar = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypePolar.setObjectName("uFieldTypePolar")
        self.uFieldTypeLayout.addWidget(self.uFieldTypePolar)
        self.uFieldTypeHeight = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeHeight.setObjectName("uFieldTypeHeight")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeHeight)
        self.uFieldTypeNone = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeNone.setObjectName("uFieldTypeNone")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeNone)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uFieldTypeLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.uVectorFieldTypeGroupBox)
        self.uVectorFieldGrid = QtWidgets.QGridLayout()
        self.uVectorFieldGrid.setObjectName("uVectorFieldGrid")
        self.uXFieldLabel = QtWidgets.QLabel(self.uVectorTab)
        self.uXFieldLabel.setObjectName("uXFieldLabel")
        self.uVectorFieldGrid.addWidget(self.uXFieldLabel, 0, 0, 1, 1)
        self.uYFieldLabel = QtWidgets.QLabel(self.uVectorTab)
        self.uYFieldLabel.setObjectName("uYFieldLabel")
        self.uVectorFieldGrid.addWidget(self.uYFieldLabel, 1, 0, 1, 1)
        self.uXField = gui.QgsFieldComboBox(self.uVectorTab)
        self.uXField.setObjectName("uXField")
        self.uVectorFieldGrid.addWidget(self.uXField, 0, 1, 1, 1)
        self.uYField = gui.QgsFieldComboBox(self.uVectorTab)
        self.uYField.setObjectName("uYField")
        self.uVectorFieldGrid.addWidget(self.uYField, 1, 1, 1, 1)
        self.uVectorFieldGrid.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.uVectorFieldGrid)
        self.uAngleFormatLayout = QtWidgets.QHBoxLayout()
        self.uAngleFormatLayout.setContentsMargins(0, -1, 0, -1)
        self.uAngleFormatLayout.setObjectName("uAngleFormatLayout")
        self.uOrientationGroupBox = QtWidgets.QGroupBox(self.uVectorTab)
        self.uOrientationGroupBox.setEnabled(True)
        self.uOrientationGroupBox.setObjectName("uOrientationGroupBox")
        self.uOrientationLayout = QtWidgets.QHBoxLayout(self.uOrientationGroupBox)
        self.uOrientationLayout.setContentsMargins(0, 0, 0, 0)
        self.uOrientationLayout.setSpacing(15)
        self.uOrientationLayout.setObjectName("uOrientationLayout")
        self.uAngleOrientationEast = QtWidgets.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationEast.setChecked(True)
        self.uAngleOrientationEast.setObjectName("uAngleOrientationEast")
        self.uOrientationLayout.addWidget(self.uAngleOrientationEast)
        self.uAngleOrientationNorth = QtWidgets.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationNorth.setObjectName("uAngleOrientationNorth")
        self.uOrientationLayout.addWidget(self.uAngleOrientationNorth)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uOrientationLayout.addItem(spacerItem1)
        self.uAngleFormatLayout.addWidget(self.uOrientationGroupBox)
        self.uAngleUnitsGroupBox = QtWidgets.QGroupBox(self.uVectorTab)
        self.uAngleUnitsGroupBox.setEnabled(True)
        self.uAngleUnitsGroupBox.setObjectName("uAngleUnitsGroupBox")
        self.uAngleUnitsLayout = QtWidgets.QHBoxLayout(self.uAngleUnitsGroupBox)
        self.uAngleUnitsLayout.setContentsMargins(0, 0, 0, 0)
        self.uAngleUnitsLayout.setSpacing(15)
        self.uAngleUnitsLayout.setObjectName("uAngleUnitsLayout")
        self.uAngleUnitsDegrees = QtWidgets.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsDegrees.setChecked(True)
        self.uAngleUnitsDegrees.setObjectName("uAngleUnitsDegrees")
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsDegrees)
        self.uAngleUnitsRadians = QtWidgets.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsRadians.setEnabled(True)
        self.uAngleUnitsRadians.setObjectName("uAngleUnitsRadians")
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsRadians)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uAngleUnitsLayout.addItem(spacerItem2)
        self.uAngleFormatLayout.addWidget(self.uAngleUnitsGroupBox)
        self.verticalLayout.addLayout(self.uAngleFormatLayout)
        self.uArrowFormatGroup = QtWidgets.QGroupBox(self.uVectorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowFormatGroup.sizePolicy().hasHeightForWidth())
        self.uArrowFormatGroup.setSizePolicy(sizePolicy)
        self.uArrowFormatGroup.setObjectName("uArrowFormatGroup")
        self.uArrowFormatLayout = QtWidgets.QVBoxLayout(self.uArrowFormatGroup)
        self.uArrowFormatLayout.setContentsMargins(0, 0, 0, 0)
        self.uArrowFormatLayout.setObjectName("uArrowFormatLayout")
        self.uArrowSizeLayout = QtWidgets.QHBoxLayout()
        self.uArrowSizeLayout.setObjectName("uArrowSizeLayout")
        self.uArrowHeadSizeLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadSizeLabel.setObjectName("uArrowHeadSizeLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSizeLabel)
        self.uArrowHeadSize = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadSize.setMinimum(-3.0)
        self.uArrowHeadSize.setMaximum(3.0)
        self.uArrowHeadSize.setSingleStep(0.1)
        self.uArrowHeadSize.setObjectName("uArrowHeadSize")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadMaxSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadMaxSizeLabel.setObjectName("uArrowHeadMaxSizeLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSizeLabel)
        self.uArrowHeadMaxSize = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadMaxSize.setObjectName("uArrowHeadMaxSize")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSize)
        self.uArrowShaftWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowShaftWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowShaftWidthLabel.setObjectName("uArrowShaftWidthLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowShaftWidthLabel)
        self.uArrowShaftWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowShaftWidth.setObjectName("uArrowShaftWidth")
        self.uArrowSizeLayout.addWidget(self.uArrowShaftWidth)
        self.uArrowBorderWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowBorderWidthLabel.setObjectName("uArrowBorderWidthLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowBorderWidthLabel)
        self.uArrowBorderWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowBorderWidth.setObjectName("uArrowBorderWidth")
        self.uArrowSizeLayout.addWidget(self.uArrowBorderWidth)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowSizeLayout.addItem(spacerItem3)
        self.uArrowFormatLayout.addLayout(self.uArrowSizeLayout)
        self.uArrowFormatLayout2 = QtWidgets.QHBoxLayout()
        self.uArrowFormatLayout2.setObjectName("uArrowFormatLayout2")
        self.uArrowBorderColorLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowBorderColorLabel.sizePolicy().hasHeightForWidth())
        self.uArrowBorderColorLabel.setSizePolicy(sizePolicy)
        self.uArrowBorderColorLabel.setObjectName("uArrowBorderColorLabel")
        self.uArrowFormatLayout2.addWidget(self.uArrowBorderColorLabel)
        self.uArrowBorderColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowBorderColor.setObjectName("uArrowBorderColor")
        self.uArrowFormatLayout2.addWidget(self.uArrowBorderColor)
        self.uFillArrowLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uFillArrowLabel.setObjectName("uFillArrowLabel")
        self.uArrowFormatLayout2.addWidget(self.uFillArrowLabel)
        self.uFillArrow = QtWidgets.QCheckBox(self.uArrowFormatGroup)
        self.uFillArrow.setText("")
        self.uFillArrow.setObjectName("uFillArrow")
        self.uArrowFormatLayout2.addWidget(self.uFillArrow)
        self.uArrowFillColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowFillColor.setObjectName("uArrowFillColor")
        self.uArrowFormatLayout2.addWidget(self.uArrowFillColor)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowFormatLayout2.addItem(spacerItem4)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatLayout2)
        self.uArrowFormatLayout_3 = QtWidgets.QHBoxLayout()
        self.uArrowFormatLayout_3.setObjectName("uArrowFormatLayout_3")
        self.uArrowHeadShapeFrontLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeFrontLabel.setObjectName("uArrowHeadShapeFrontLabel")
        self.uArrowFormatLayout_3.addWidget(self.uArrowHeadShapeFrontLabel)
        self.uArrowHeadShapeFront = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeFront.setMinimum(-3.0)
        self.uArrowHeadShapeFront.setMaximum(3.0)
        self.uArrowHeadShapeFront.setSingleStep(0.1)
        self.uArrowHeadShapeFront.setObjectName("uArrowHeadShapeFront")
        self.uArrowFormatLayout_3.addWidget(self.uArrowHeadShapeFront)
        self.uArrowHeadShapeBackLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeBackLabel.setObjectName("uArrowHeadShapeBackLabel")
        self.uArrowFormatLayout_3.addWidget(self.uArrowHeadShapeBackLabel)
        self.uArrowHeadShapeBack = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeBack.setMinimum(-3.0)
        self.uArrowHeadShapeBack.setMaximum(3.0)
        self.uArrowHeadShapeBack.setSingleStep(0.1)
        self.uArrowHeadShapeBack.setObjectName("uArrowHeadShapeBack")
        self.uArrowFormatLayout_3.addWidget(self.uArrowHeadShapeBack)
        self.uArrowHeadShapeCentreLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeCentreLabel.setObjectName("uArrowHeadShapeCentreLabel")
        self.uArrowFormatLayout_3.addWidget(self.uArrowHeadShapeCentreLabel)
        self.uArrowHeadShapeCentre = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeCentre.setMinimum(-3.0)
        self.uArrowHeadShapeCentre.setMaximum(3.0)
        self.uArrowHeadShapeCentre.setSingleStep(0.1)
        self.uArrowHeadShapeCentre.setObjectName("uArrowHeadShapeCentre")
        self.uArrowFormatLayout_3.addWidget(self.uArrowHeadShapeCentre)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowFormatLayout_3.addItem(spacerItem5)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatLayout_3)
        self.verticalLayout.addWidget(self.uArrowFormatGroup)
        self.uTabManager.addTab(self.uVectorTab, "")
        self.uEllipseTab = QtWidgets.QWidget()
        self.uEllipseTab.setObjectName("uEllipseTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.uEllipseTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uErrorEllipseTypeGroupBox = QtWidgets.QGroupBox(self.uEllipseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uErrorEllipseTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uErrorEllipseTypeGroupBox.setSizePolicy(sizePolicy)
        self.uErrorEllipseTypeGroupBox.setObjectName("uErrorEllipseTypeGroupBox")
        self.uFieldTypeLayout_2 = QtWidgets.QHBoxLayout(self.uErrorEllipseTypeGroupBox)
        self.uFieldTypeLayout_2.setContentsMargins(0, 0, 0, 0)
        self.uFieldTypeLayout_2.setSpacing(15)
        self.uFieldTypeLayout_2.setObjectName("uFieldTypeLayout_2")
        self.uEllipseTypeCovariance = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCovariance.setChecked(False)
        self.uEllipseTypeCovariance.setObjectName("uEllipseTypeCovariance")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCovariance)
        self.uEllipseTypeAxes = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeAxes.setObjectName("uEllipseTypeAxes")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeAxes)
        self.uEllipseTypeCircular = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCircular.setObjectName("uEllipseTypeCircular")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCircular)
        self.uEllipseTypeHeight = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeHeight.setObjectName("uEllipseTypeHeight")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeHeight)
        self.uEllipseTypeNone = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeNone.setChecked(True)
        self.uEllipseTypeNone.setObjectName("uEllipseTypeNone")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeNone)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uFieldTypeLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.uErrorEllipseTypeGroupBox)
        self.uVectorFieldGrid_2 = QtWidgets.QGridLayout()
        self.uVectorFieldGrid_2.setObjectName("uVectorFieldGrid_2")
        self.uEmaxFieldLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEmaxFieldLabel.setObjectName("uEmaxFieldLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxFieldLabel, 0, 0, 1, 1)
        self.uEminFieldLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEminFieldLabel.setObjectName("uEminFieldLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEminFieldLabel, 1, 0, 1, 1)
        self.uEllipseScaleLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEllipseScaleLabel.setObjectName("uEllipseScaleLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEllipseScaleLabel, 3, 0, 1, 1)
        self.uArrowScaleLayout_2 = QtWidgets.QHBoxLayout()
        self.uArrowScaleLayout_2.setObjectName("uArrowScaleLayout_2")
        self.uEllipseScale = QtWidgets.QLineEdit(self.uEllipseTab)
        self.uEllipseScale.setObjectName("uEllipseScale")
        self.uArrowScaleLayout_2.addWidget(self.uEllipseScale)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowScaleLayout_2.addItem(spacerItem7)
        self.uVectorFieldGrid_2.addLayout(self.uArrowScaleLayout_2, 3, 2, 1, 1)
        self.uEmaxAzimuthFieldLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEmaxAzimuthFieldLabel.setObjectName("uEmaxAzimuthFieldLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxAzimuthFieldLabel, 2, 0, 1, 1)
        self.uEmaxField = gui.QgsFieldComboBox(self.uEllipseTab)
        self.uEmaxField.setObjectName("uEmaxField")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxField, 0, 2, 1, 1)
        self.uEminField = gui.QgsFieldComboBox(self.uEllipseTab)
        self.uEminField.setObjectName("uEminField")
        self.uVectorFieldGrid_2.addWidget(self.uEminField, 1, 2, 1, 1)
        self.uEmaxAzimuthField = gui.QgsFieldComboBox(self.uEllipseTab)
        self.uEmaxAzimuthField.setObjectName("uEmaxAzimuthField")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxAzimuthField, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.uVectorFieldGrid_2)
        self.uAxisAngleFormatLayout = QtWidgets.QHBoxLayout()
        self.uAxisAngleFormatLayout.setContentsMargins(-1, 0, -1, -1)
        self.uAxisAngleFormatLayout.setObjectName("uAxisAngleFormatLayout")
        self.uAxisOrientationGroupBox = QtWidgets.QGroupBox(self.uEllipseTab)
        self.uAxisOrientationGroupBox.setEnabled(True)
        self.uAxisOrientationGroupBox.setObjectName("uAxisOrientationGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.uAxisOrientationGroupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uEllipseOrientationEast = QtWidgets.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationEast.setChecked(True)
        self.uEllipseOrientationEast.setObjectName("uEllipseOrientationEast")
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationEast)
        self.uEllipseOrientationNorth = QtWidgets.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationNorth.setObjectName("uEllipseOrientationNorth")
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationNorth)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisOrientationGroupBox)
        self.uAxisAngleUnitsGroupBox = QtWidgets.QGroupBox(self.uEllipseTab)
        self.uAxisAngleUnitsGroupBox.setEnabled(True)
        self.uAxisAngleUnitsGroupBox.setObjectName("uAxisAngleUnitsGroupBox")
        self.uAngleUnitsLayout_2 = QtWidgets.QHBoxLayout(self.uAxisAngleUnitsGroupBox)
        self.uAngleUnitsLayout_2.setContentsMargins(0, 0, 0, 0)
        self.uAngleUnitsLayout_2.setSpacing(15)
        self.uAngleUnitsLayout_2.setObjectName("uAngleUnitsLayout_2")
        self.uEllipseAngleUnitsDegrees = QtWidgets.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsDegrees.setChecked(True)
        self.uEllipseAngleUnitsDegrees.setObjectName("uEllipseAngleUnitsDegrees")
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsDegrees)
        self.uEllipseAngleUnitsRadians = QtWidgets.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsRadians.setEnabled(True)
        self.uEllipseAngleUnitsRadians.setObjectName("uEllipseAngleUnitsRadians")
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsRadians)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uAngleUnitsLayout_2.addItem(spacerItem9)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisAngleUnitsGroupBox)
        self.verticalLayout_2.addLayout(self.uAxisAngleFormatLayout)
        self.uEllipseFormatGroup = QtWidgets.QGroupBox(self.uEllipseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uEllipseFormatGroup.sizePolicy().hasHeightForWidth())
        self.uEllipseFormatGroup.setSizePolicy(sizePolicy)
        self.uEllipseFormatGroup.setObjectName("uEllipseFormatGroup")
        self.uArrowFormatLayout_2 = QtWidgets.QVBoxLayout(self.uEllipseFormatGroup)
        self.uArrowFormatLayout_2.setContentsMargins(0, 0, 0, 0)
        self.uArrowFormatLayout_2.setSpacing(6)
        self.uArrowFormatLayout_2.setObjectName("uArrowFormatLayout_2")
        self.uEllipseFormatLayout1 = QtWidgets.QHBoxLayout()
        self.uEllipseFormatLayout1.setObjectName("uEllipseFormatLayout1")
        self.uEllipseWidthLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uEllipseWidthLabel.setObjectName("uEllipseWidthLabel")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseWidthLabel)
        self.uEllipseBorderWidth = QtWidgets.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseBorderWidth.setObjectName("uEllipseBorderWidth")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseBorderWidth)
        self.uTickSizeLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uTickSizeLabel.setObjectName("uTickSizeLabel")
        self.uEllipseFormatLayout1.addWidget(self.uTickSizeLabel)
        self.uEllipseTickSize = QtWidgets.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseTickSize.setObjectName("uEllipseTickSize")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseTickSize)
        self.uDrawEllipseLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uDrawEllipseLabel.setObjectName("uDrawEllipseLabel")
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseLabel)
        self.uDrawEllipse = QtWidgets.QCheckBox(self.uEllipseFormatGroup)
        self.uDrawEllipse.setText("")
        self.uDrawEllipse.setObjectName("uDrawEllipse")
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipse)
        self.uDrawEllipseAxesLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uDrawEllipseAxesLabel.setObjectName("uDrawEllipseAxesLabel")
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseAxesLabel)
        self.uDrawEllipseAxes = QtWidgets.QCheckBox(self.uEllipseFormatGroup)
        self.uDrawEllipseAxes.setText("")
        self.uDrawEllipseAxes.setObjectName("uDrawEllipseAxes")
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseAxes)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uEllipseFormatLayout1.addItem(spacerItem10)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseFormatLayout1)
        self.uEllipseFormatLayout2 = QtWidgets.QHBoxLayout()
        self.uEllipseFormatLayout2.setContentsMargins(-1, 6, -1, -1)
        self.uEllipseFormatLayout2.setObjectName("uEllipseFormatLayout2")
        self.uEllipseColorLayoutLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseColorLayoutLabel.setObjectName("uEllipseColorLayoutLabel")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseColorLayoutLabel)
        self.uEllipseBorderColor = gui.QgsColorButton(self.uEllipseFormatGroup)
        self.uEllipseBorderColor.setObjectName("uEllipseBorderColor")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseFillColorLabel.setObjectName("uEllipseFillColorLabel")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseFillColorLabel)
        self.uFillEllipse = QtWidgets.QCheckBox(self.uEllipseFormatGroup)
        self.uFillEllipse.setText("")
        self.uFillEllipse.setObjectName("uFillEllipse")
        self.uEllipseFormatLayout2.addWidget(self.uFillEllipse)
        self.uEllipseFillColor = gui.QgsColorButton(self.uEllipseFormatGroup)
        self.uEllipseFillColor.setObjectName("uEllipseFillColor")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseFillColor)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uEllipseFormatLayout2.addItem(spacerItem11)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseFormatLayout2)
        self.verticalLayout_2.addWidget(self.uEllipseFormatGroup)
        self.uTabManager.addTab(self.uEllipseTab, "")
        self.verticalLayout_4.addWidget(self.uTabManager)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uSymbolUnitsLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uSymbolUnitsLabel.setObjectName("uSymbolUnitsLabel")
        self.horizontalLayout_3.addWidget(self.uSymbolUnitsLabel)
        self.uSymbolUnits = QtWidgets.QPushButton(VectorFieldRendererWidget)
        self.uSymbolUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uSymbolUnits.setObjectName("uSymbolUnits")
        self.horizontalLayout_3.addWidget(self.uSymbolUnits)
        self.uArrowBaseSizeLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uArrowBaseSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowBaseSizeLabel.setObjectName("uArrowBaseSizeLabel")
        self.horizontalLayout_3.addWidget(self.uArrowBaseSizeLabel)
        self.uArrowBaseSize = QtWidgets.QDoubleSpinBox(VectorFieldRendererWidget)
        self.uArrowBaseSize.setObjectName("uArrowBaseSize")
        self.horizontalLayout_3.addWidget(self.uArrowBaseSize)
        self.uBaseBorderColorLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uBaseBorderColorLabel.setObjectName("uBaseBorderColorLabel")
        self.horizontalLayout_3.addWidget(self.uBaseBorderColorLabel)
        self.uBaseBorderColor = gui.QgsColorButton(VectorFieldRendererWidget)
        self.uBaseBorderColor.setObjectName("uBaseBorderColor")
        self.horizontalLayout_3.addWidget(self.uBaseBorderColor)
        self.uBaseColorLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uBaseColorLabel.setObjectName("uBaseColorLabel")
        self.horizontalLayout_3.addWidget(self.uBaseColorLabel)
        self.uFillBase = QtWidgets.QCheckBox(VectorFieldRendererWidget)
        self.uFillBase.setText("")
        self.uFillBase.setObjectName("uFillBase")
        self.horizontalLayout_3.addWidget(self.uFillBase)
        self.uBaseColor = gui.QgsColorButton(VectorFieldRendererWidget)
        self.uBaseColor.setObjectName("uBaseColor")
        self.horizontalLayout_3.addWidget(self.uBaseColor)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.uVectorAlignmentLayout = QtWidgets.QHBoxLayout()
        self.uVectorAlignmentLayout.setContentsMargins(-1, 0, 0, -1)
        self.uVectorAlignmentLayout.setObjectName("uVectorAlignmentLayout")
        self.label_3 = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.uVectorAlignmentLayout.addWidget(self.label_3)
        self.uAlignToMapNorth = QtWidgets.QCheckBox(VectorFieldRendererWidget)
        self.uAlignToMapNorth.setText("")
        self.uAlignToMapNorth.setObjectName("uAlignToMapNorth")
        self.uVectorAlignmentLayout.addWidget(self.uAlignToMapNorth)
        self.label_2 = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.label_2.setToolTip("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.uVectorAlignmentLayout.addWidget(self.label_2)
        self.uVectorIsTrueNorth = QtWidgets.QCheckBox(VectorFieldRendererWidget)
        self.uVectorIsTrueNorth.setText("")
        self.uVectorIsTrueNorth.setObjectName("uVectorIsTrueNorth")
        self.uVectorAlignmentLayout.addWidget(self.uVectorIsTrueNorth)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uVectorAlignmentLayout.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.uVectorAlignmentLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 9, 9, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uArrowScaleLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uArrowScaleLabel.setObjectName("uArrowScaleLabel")
        self.horizontalLayout_4.addWidget(self.uArrowScaleLabel)
        self.uArrowScale = QtWidgets.QLineEdit(VectorFieldRendererWidget)
        self.uArrowScale.setObjectName("uArrowScale")
        self.horizontalLayout_4.addWidget(self.uArrowScale)
        self.uScaleUnits = QtWidgets.QPushButton(VectorFieldRendererWidget)
        self.uScaleUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uScaleUnits.setObjectName("uScaleUnits")
        self.horizontalLayout_4.addWidget(self.uScaleUnits)
        self.uScaleGroupLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uScaleGroupLabel.setObjectName("uScaleGroupLabel")
        self.horizontalLayout_4.addWidget(self.uScaleGroupLabel)
        self.uScaleGroup = QtWidgets.QLineEdit(VectorFieldRendererWidget)
        self.uScaleGroup.setObjectName("uScaleGroup")
        self.horizontalLayout_4.addWidget(self.uScaleGroup)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.uVectorLegendFieldsLayout = QtWidgets.QHBoxLayout()
        self.uVectorLegendFieldsLayout.setContentsMargins(-1, 0, -1, -1)
        self.uVectorLegendFieldsLayout.setObjectName("uVectorLegendFieldsLayout")
        self.uLegendTextLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uLegendTextLabel.setObjectName("uLegendTextLabel")
        self.uVectorLegendFieldsLayout.addWidget(self.uLegendTextLabel)
        self.uLegendText = QtWidgets.QLineEdit(VectorFieldRendererWidget)
        self.uLegendText.setObjectName("uLegendText")
        self.uVectorLegendFieldsLayout.addWidget(self.uLegendText)
        self.uScaleBoxTextLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uScaleBoxTextLabel.setObjectName("uScaleBoxTextLabel")
        self.uVectorLegendFieldsLayout.addWidget(self.uScaleBoxTextLabel)
        self.uScaleBoxText = QtWidgets.QLineEdit(VectorFieldRendererWidget)
        self.uScaleBoxText.setObjectName("uScaleBoxText")
        self.uVectorLegendFieldsLayout.addWidget(self.uScaleBoxText)
        self.uShowScaleBoxLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uShowScaleBoxLabel.setObjectName("uShowScaleBoxLabel")
        self.uVectorLegendFieldsLayout.addWidget(self.uShowScaleBoxLabel)
        self.uShowInScaleBox = QtWidgets.QCheckBox(VectorFieldRendererWidget)
        self.uShowInScaleBox.setText("")
        self.uShowInScaleBox.setObjectName("uShowInScaleBox")
        self.uVectorLegendFieldsLayout.addWidget(self.uShowInScaleBox)
        self.uHelpButton = QtWidgets.QPushButton(VectorFieldRendererWidget)
        self.uHelpButton.setObjectName("uHelpButton")
        self.uVectorLegendFieldsLayout.addWidget(self.uHelpButton)
        self.verticalLayout_4.addLayout(self.uVectorLegendFieldsLayout)
        self.uArrowHeadSizeLabel.setBuddy(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel.setBuddy(self.uArrowHeadMaxSize)
        self.uArrowShaftWidthLabel.setBuddy(self.uArrowShaftWidth)
        self.uArrowBorderWidthLabel.setBuddy(self.uArrowBorderWidth)
        self.uArrowBorderColorLabel.setBuddy(self.uArrowBorderColor)
        self.uFillArrowLabel.setBuddy(self.uFillArrow)
        self.uArrowHeadShapeFrontLabel.setBuddy(self.uArrowHeadShapeFront)
        self.uArrowHeadShapeBackLabel.setBuddy(self.uArrowHeadShapeBack)
        self.uArrowHeadShapeCentreLabel.setBuddy(self.uArrowHeadShapeCentre)
        self.uEllipseScaleLabel.setBuddy(self.uEllipseScale)
        self.uEllipseWidthLabel.setBuddy(self.uEllipseBorderWidth)
        self.uDrawEllipseLabel.setBuddy(self.uFillEllipse)
        self.uEllipseColorLayoutLabel.setBuddy(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel.setBuddy(self.uEllipseFillColor)
        self.uSymbolUnitsLabel.setBuddy(self.uSymbolUnits)
        self.uArrowBaseSizeLabel.setBuddy(self.uArrowBaseSize)
        self.uBaseBorderColorLabel.setBuddy(self.uBaseBorderColor)
        self.uBaseColorLabel.setBuddy(self.uFillBase)
        self.label_3.setBuddy(self.uAlignToMapNorth)
        self.label_2.setBuddy(self.uVectorIsTrueNorth)
        self.uArrowScaleLabel.setBuddy(self.uArrowScale)
        self.uScaleGroupLabel.setBuddy(self.uScaleGroup)
        self.uLegendTextLabel.setBuddy(self.uLegendText)
        self.uScaleBoxTextLabel.setBuddy(self.uScaleBoxText)
        self.uShowScaleBoxLabel.setBuddy(self.uShowInScaleBox)

        self.retranslateUi(VectorFieldRendererWidget)
        self.uTabManager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VectorFieldRendererWidget)
        VectorFieldRendererWidget.setTabOrder(self.uTabManager, self.uFieldTypeCartesian)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeCartesian, self.uFieldTypePolar)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypePolar, self.uFieldTypeHeight)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeHeight, self.uFieldTypeNone)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeNone, self.uAngleOrientationEast)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationEast, self.uAngleOrientationNorth)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationNorth, self.uAngleUnitsDegrees)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsDegrees, self.uAngleUnitsRadians)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsRadians, self.uArrowHeadSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadSize, self.uArrowHeadMaxSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadMaxSize, self.uArrowShaftWidth)
        VectorFieldRendererWidget.setTabOrder(self.uArrowShaftWidth, self.uArrowBorderColor)
        VectorFieldRendererWidget.setTabOrder(self.uArrowBorderColor, self.uFillArrow)
        VectorFieldRendererWidget.setTabOrder(self.uFillArrow, self.uArrowFillColor)
        VectorFieldRendererWidget.setTabOrder(self.uArrowFillColor, self.uArrowHeadShapeFront)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadShapeFront, self.uArrowHeadShapeBack)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadShapeBack, self.uArrowHeadShapeCentre)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadShapeCentre, self.uEllipseTypeCovariance)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseTypeCovariance, self.uEllipseTypeAxes)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseTypeAxes, self.uEllipseTypeCircular)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseTypeCircular, self.uEllipseTypeHeight)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseTypeHeight, self.uEllipseTypeNone)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseTypeNone, self.uEllipseScale)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseScale, self.uEllipseOrientationEast)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseOrientationEast, self.uEllipseOrientationNorth)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseOrientationNorth, self.uEllipseAngleUnitsDegrees)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseAngleUnitsDegrees, self.uEllipseAngleUnitsRadians)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseAngleUnitsRadians, self.uEllipseBorderWidth)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseBorderWidth, self.uEllipseTickSize)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseTickSize, self.uDrawEllipse)
        VectorFieldRendererWidget.setTabOrder(self.uDrawEllipse, self.uDrawEllipseAxes)
        VectorFieldRendererWidget.setTabOrder(self.uDrawEllipseAxes, self.uEllipseBorderColor)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseBorderColor, self.uFillEllipse)
        VectorFieldRendererWidget.setTabOrder(self.uFillEllipse, self.uEllipseFillColor)
        VectorFieldRendererWidget.setTabOrder(self.uEllipseFillColor, self.uSymbolUnits)
        VectorFieldRendererWidget.setTabOrder(self.uSymbolUnits, self.uArrowBaseSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowBaseSize, self.uBaseBorderColor)
        VectorFieldRendererWidget.setTabOrder(self.uBaseBorderColor, self.uFillBase)
        VectorFieldRendererWidget.setTabOrder(self.uFillBase, self.uBaseColor)
        VectorFieldRendererWidget.setTabOrder(self.uBaseColor, self.uAlignToMapNorth)
        VectorFieldRendererWidget.setTabOrder(self.uAlignToMapNorth, self.uVectorIsTrueNorth)
        VectorFieldRendererWidget.setTabOrder(self.uVectorIsTrueNorth, self.uArrowScale)
        VectorFieldRendererWidget.setTabOrder(self.uArrowScale, self.uScaleUnits)
        VectorFieldRendererWidget.setTabOrder(self.uScaleUnits, self.uScaleGroup)
        VectorFieldRendererWidget.setTabOrder(self.uScaleGroup, self.uLegendText)
        VectorFieldRendererWidget.setTabOrder(self.uLegendText, self.uScaleBoxText)
        VectorFieldRendererWidget.setTabOrder(self.uScaleBoxText, self.uShowInScaleBox)
        VectorFieldRendererWidget.setTabOrder(self.uShowInScaleBox, self.uHelpButton)

    def retranslateUi(self, VectorFieldRendererWidget):
        _translate = QtCore.QCoreApplication.translate
        VectorFieldRendererWidget.setWindowTitle(_translate("VectorFieldRendererWidget", "Form"))
        self.uVectorFieldTypeGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Vector field type"))
        self.uFieldTypeCartesian.setText(_translate("VectorFieldRendererWidget", "Cartesian (XY) field"))
        self.uFieldTypePolar.setText(_translate("VectorFieldRendererWidget", "Polar (length,angle) field"))
        self.uFieldTypeHeight.setText(_translate("VectorFieldRendererWidget", "Height only"))
        self.uFieldTypeNone.setText(_translate("VectorFieldRendererWidget", "None"))
        self.uXFieldLabel.setText(_translate("VectorFieldRendererWidget", "X attribute"))
        self.uYFieldLabel.setText(_translate("VectorFieldRendererWidget", "Y attribute"))
        self.uOrientationGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle orientation"))
        self.uAngleOrientationEast.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation"))
        self.uAngleOrientationEast.setText(_translate("VectorFieldRendererWidget", "North from east"))
        self.uAngleOrientationNorth.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation"))
        self.uAngleOrientationNorth.setText(_translate("VectorFieldRendererWidget", "East from north"))
        self.uAngleUnitsGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle units"))
        self.uAngleUnitsDegrees.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units"))
        self.uAngleUnitsDegrees.setText(_translate("VectorFieldRendererWidget", "Degrees"))
        self.uAngleUnitsRadians.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units"))
        self.uAngleUnitsRadians.setText(_translate("VectorFieldRendererWidget", "Radians"))
        self.uArrowFormatGroup.setTitle(_translate("VectorFieldRendererWidget", "Arrow format"))
        self.uArrowHeadSizeLabel.setText(_translate("VectorFieldRendererWidget", "Size: Head (relative)"))
        self.uArrowHeadSize.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uArrowHeadMaxSizeLabel.setText(_translate("VectorFieldRendererWidget", "Head (max)"))
        self.uArrowHeadMaxSize.setToolTip(_translate("VectorFieldRendererWidget", "Maximum arrow head size"))
        self.uArrowShaftWidthLabel.setText(_translate("VectorFieldRendererWidget", " Shaft width"))
        self.uArrowShaftWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft"))
        self.uArrowBorderWidthLabel.setText(_translate("VectorFieldRendererWidget", "Border width"))
        self.uArrowBorderWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft"))
        self.uArrowBorderColorLabel.setText(_translate("VectorFieldRendererWidget", "Colour: Head border/shaft"))
        self.uArrowBorderColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour"))
        self.uArrowBorderColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uFillArrowLabel.setText(_translate("VectorFieldRendererWidget", "Fill arrow?"))
        self.uArrowFillColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour"))
        self.uArrowFillColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uArrowHeadShapeFrontLabel.setText(_translate("VectorFieldRendererWidget", "Arrow shape (relative x coords): front"))
        self.uArrowHeadShapeFront.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uArrowHeadShapeBackLabel.setText(_translate("VectorFieldRendererWidget", "back outside"))
        self.uArrowHeadShapeBack.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uArrowHeadShapeCentreLabel.setText(_translate("VectorFieldRendererWidget", "back centre"))
        self.uArrowHeadShapeCentre.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uVectorTab), _translate("VectorFieldRendererWidget", "Vector field"))
        self.uErrorEllipseTypeGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Error ellipse type"))
        self.uEllipseTypeCovariance.setText(_translate("VectorFieldRendererWidget", "Covariance matrix"))
        self.uEllipseTypeAxes.setText(_translate("VectorFieldRendererWidget", "Ellipses axes"))
        self.uEllipseTypeCircular.setText(_translate("VectorFieldRendererWidget", "Circular"))
        self.uEllipseTypeHeight.setText(_translate("VectorFieldRendererWidget", "Height"))
        self.uEllipseTypeNone.setText(_translate("VectorFieldRendererWidget", "None"))
        self.uEmaxFieldLabel.setText(_translate("VectorFieldRendererWidget", "Major axis error"))
        self.uEminFieldLabel.setText(_translate("VectorFieldRendererWidget", "Minor axis error"))
        self.uEllipseScaleLabel.setText(_translate("VectorFieldRendererWidget", "Ellipse scale factor"))
        self.uEmaxAzimuthFieldLabel.setText(_translate("VectorFieldRendererWidget", "Major axis azimuth"))
        self.uAxisOrientationGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Ellipse axis orientation"))
        self.uEllipseOrientationEast.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation"))
        self.uEllipseOrientationEast.setText(_translate("VectorFieldRendererWidget", "North from east"))
        self.uEllipseOrientationNorth.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation"))
        self.uEllipseOrientationNorth.setText(_translate("VectorFieldRendererWidget", "East from north"))
        self.uAxisAngleUnitsGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle units"))
        self.uEllipseAngleUnitsDegrees.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units"))
        self.uEllipseAngleUnitsDegrees.setText(_translate("VectorFieldRendererWidget", "Degrees"))
        self.uEllipseAngleUnitsRadians.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units"))
        self.uEllipseAngleUnitsRadians.setText(_translate("VectorFieldRendererWidget", "Radians"))
        self.uEllipseFormatGroup.setTitle(_translate("VectorFieldRendererWidget", "Ellipse format"))
        self.uEllipseWidthLabel.setText(_translate("VectorFieldRendererWidget", "Border width"))
        self.uEllipseBorderWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft"))
        self.uTickSizeLabel.setText(_translate("VectorFieldRendererWidget", "Tick size "))
        self.uEllipseTickSize.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft"))
        self.uDrawEllipseLabel.setText(_translate("VectorFieldRendererWidget", "Draw ellipse"))
        self.uDrawEllipseAxesLabel.setText(_translate("VectorFieldRendererWidget", "Draw ellipse axes"))
        self.uEllipseColorLayoutLabel.setText(_translate("VectorFieldRendererWidget", "Colours: Border/axes"))
        self.uEllipseBorderColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour"))
        self.uEllipseBorderColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uEllipseFillColorLabel.setText(_translate("VectorFieldRendererWidget", "Fill?"))
        self.uEllipseFillColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base symbol colour"))
        self.uEllipseFillColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uEllipseTab), _translate("VectorFieldRendererWidget", "Error ellipse"))
        self.uSymbolUnitsLabel.setText(_translate("VectorFieldRendererWidget", "Symbol units"))
        self.uSymbolUnits.setText(_translate("VectorFieldRendererWidget", "Millimeter"))
        self.uArrowBaseSizeLabel.setText(_translate("VectorFieldRendererWidget", "Base size"))
        self.uArrowBaseSize.setToolTip(_translate("VectorFieldRendererWidget", "Size of the arrow base symbol"))
        self.uBaseBorderColorLabel.setText(_translate("VectorFieldRendererWidget", "Colours: Border"))
        self.uBaseBorderColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base border colour"))
        self.uBaseBorderColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uBaseColorLabel.setText(_translate("VectorFieldRendererWidget", "Fill?"))
        self.uBaseColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base symbol colour"))
        self.uBaseColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.label_3.setText(_translate("VectorFieldRendererWidget", "Align vector with map north"))
        self.uAlignToMapNorth.setToolTip(_translate("VectorFieldRendererWidget", "<html><head/><body><p>If selected the vector is drawn in terms of true north on the map, otherwise a north vector is drawn upwards on the map regardless of the map projection or map canvas rotation.  </p></body></html>"))
        self.label_2.setText(_translate("VectorFieldRendererWidget", "Vector defined relative to true north"))
        self.uVectorIsTrueNorth.setToolTip(_translate("VectorFieldRendererWidget", "<html><head/><body><p>If selected the vector is defined in terms of geographic north (true north) even if the layer coordinate reference system is a projection. Otherwise the vector is defined in terms of projection north for layer coordinate systems. Has no effect for geographic layer coordinate systems or for height only vectors.</p></body></html>"))
        self.uArrowScaleLabel.setText(_translate("VectorFieldRendererWidget", "Scale:  "))
        self.uScaleUnits.setText(_translate("VectorFieldRendererWidget", "Millimeter"))
        self.uScaleGroupLabel.setText(_translate("VectorFieldRendererWidget", "    Scale group"))
        self.uLegendTextLabel.setText(_translate("VectorFieldRendererWidget", "Legend text"))
        self.uScaleBoxTextLabel.setText(_translate("VectorFieldRendererWidget", "Scale box text"))
        self.uShowScaleBoxLabel.setText(_translate("VectorFieldRendererWidget", "Show?"))
        self.uHelpButton.setText(_translate("VectorFieldRendererWidget", "Help"))

from qgis import gui
