# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VectorFieldRendererWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VectorFieldRendererWidget(object):
    def setupUi(self, VectorFieldRendererWidget):
        VectorFieldRendererWidget.setObjectName("VectorFieldRendererWidget")
        VectorFieldRendererWidget.resize(791, 403)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VectorFieldRendererWidget.sizePolicy().hasHeightForWidth())
        VectorFieldRendererWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(VectorFieldRendererWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.uTabManager = QtWidgets.QWidget(VectorFieldRendererWidget)
        self.uTabManager.setObjectName("uTabManager")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.uTabManager)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uVectorFieldTypeGroupBox = QtWidgets.QGroupBox(self.uTabManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uVectorFieldTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uVectorFieldTypeGroupBox.setSizePolicy(sizePolicy)
        self.uVectorFieldTypeGroupBox.setObjectName("uVectorFieldTypeGroupBox")
        self.uFieldTypeLayout = QtWidgets.QHBoxLayout(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeLayout.setContentsMargins(0, 0, 0, 0)
        self.uFieldTypeLayout.setObjectName("uFieldTypeLayout")
        self.uFieldTypeCartesian = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeCartesian.setChecked(True)
        self.uFieldTypeCartesian.setObjectName("uFieldTypeCartesian")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeCartesian)
        self.uFieldTypePolar = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypePolar.setObjectName("uFieldTypePolar")
        self.uFieldTypeLayout.addWidget(self.uFieldTypePolar)
        self.uFieldTypeHeight = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeHeight.setObjectName("uFieldTypeHeight")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeHeight)
        self.uFieldTypeNone = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeNone.setEnabled(False)
        self.uFieldTypeNone.setObjectName("uFieldTypeNone")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeNone)
        self.verticalLayout.addWidget(self.uVectorFieldTypeGroupBox)
        self.uVectorFieldGrid = QtWidgets.QGridLayout()
        self.uVectorFieldGrid.setObjectName("uVectorFieldGrid")
        self.uXFieldLabel = QtWidgets.QLabel(self.uTabManager)
        self.uXFieldLabel.setObjectName("uXFieldLabel")
        self.uVectorFieldGrid.addWidget(self.uXFieldLabel, 0, 0, 1, 1)
        self.uYFieldLabel = QtWidgets.QLabel(self.uTabManager)
        self.uYFieldLabel.setObjectName("uYFieldLabel")
        self.uVectorFieldGrid.addWidget(self.uYFieldLabel, 1, 0, 1, 1)
        self.uXField = gui.QgsFieldComboBox(self.uTabManager)
        self.uXField.setObjectName("uXField")
        self.uVectorFieldGrid.addWidget(self.uXField, 0, 1, 1, 1)
        self.uYField = gui.QgsFieldComboBox(self.uTabManager)
        self.uYField.setObjectName("uYField")
        self.uVectorFieldGrid.addWidget(self.uYField, 1, 1, 1, 1)
        self.uVectorFieldGrid.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.uVectorFieldGrid)
        self.uAngleFormatLayout = QtWidgets.QHBoxLayout()
        self.uAngleFormatLayout.setContentsMargins(0, -1, 0, -1)
        self.uAngleFormatLayout.setObjectName("uAngleFormatLayout")
        self.uOrientationGroupBox = QtWidgets.QGroupBox(self.uTabManager)
        self.uOrientationGroupBox.setEnabled(True)
        self.uOrientationGroupBox.setObjectName("uOrientationGroupBox")
        self.uOrientationLayout = QtWidgets.QHBoxLayout(self.uOrientationGroupBox)
        self.uOrientationLayout.setContentsMargins(9, 0, 9, 0)
        self.uOrientationLayout.setSpacing(6)
        self.uOrientationLayout.setObjectName("uOrientationLayout")
        self.uAngleOrientationEast = QtWidgets.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationEast.setChecked(True)
        self.uAngleOrientationEast.setObjectName("uAngleOrientationEast")
        self.uOrientationLayout.addWidget(self.uAngleOrientationEast)
        self.uAngleOrientationNorth = QtWidgets.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationNorth.setObjectName("uAngleOrientationNorth")
        self.uOrientationLayout.addWidget(self.uAngleOrientationNorth)
        self.uAngleFormatLayout.addWidget(self.uOrientationGroupBox)
        self.uAngleUnitsGroupBox = QtWidgets.QGroupBox(self.uTabManager)
        self.uAngleUnitsGroupBox.setEnabled(True)
        self.uAngleUnitsGroupBox.setObjectName("uAngleUnitsGroupBox")
        self.uAngleUnitsLayout = QtWidgets.QHBoxLayout(self.uAngleUnitsGroupBox)
        self.uAngleUnitsLayout.setContentsMargins(-1, 0, -1, 0)
        self.uAngleUnitsLayout.setObjectName("uAngleUnitsLayout")
        self.uAngleUnitsDegrees = QtWidgets.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsDegrees.setChecked(True)
        self.uAngleUnitsDegrees.setObjectName("uAngleUnitsDegrees")
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsDegrees)
        self.uAngleUnitsRadians = QtWidgets.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsRadians.setEnabled(True)
        self.uAngleUnitsRadians.setObjectName("uAngleUnitsRadians")
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsRadians)
        self.uAngleFormatLayout.addWidget(self.uAngleUnitsGroupBox)
        self.verticalLayout.addLayout(self.uAngleFormatLayout)
        self.uArrowFormatGroup = QtWidgets.QGroupBox(self.uTabManager)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowFormatGroup.sizePolicy().hasHeightForWidth())
        self.uArrowFormatGroup.setSizePolicy(sizePolicy)
        self.uArrowFormatGroup.setObjectName("uArrowFormatGroup")
        self.uArrowFormatLayout = QtWidgets.QVBoxLayout(self.uArrowFormatGroup)
        self.uArrowFormatLayout.setContentsMargins(0, 0, 0, 0)
        self.uArrowFormatLayout.setObjectName("uArrowFormatLayout")
        self.uArrowSizeLayout = QtWidgets.QHBoxLayout()
        self.uArrowSizeLayout.setObjectName("uArrowSizeLayout")
        self.uArrowHeadSizeLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadSizeLabel.setObjectName("uArrowHeadSizeLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSizeLabel)
        self.uArrowHeadSize = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadSize.setMinimum(-3.0)
        self.uArrowHeadSize.setMaximum(3.0)
        self.uArrowHeadSize.setSingleStep(0.1)
        self.uArrowHeadSize.setObjectName("uArrowHeadSize")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadMaxSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadMaxSizeLabel.setObjectName("uArrowHeadMaxSizeLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSizeLabel)
        self.uArrowHeadMaxSize = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadMaxSize.setObjectName("uArrowHeadMaxSize")
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSize)
        self.uHeadWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uHeadWidthLabel.setObjectName("uHeadWidthLabel")
        self.uArrowSizeLayout.addWidget(self.uHeadWidthLabel)
        self.uHeadWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uHeadWidth.setObjectName("uHeadWidth")
        self.uArrowSizeLayout.addWidget(self.uHeadWidth)
        self.uArrowWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowWidthLabel.setObjectName("uArrowWidthLabel")
        self.uArrowSizeLayout.addWidget(self.uArrowWidthLabel)
        self.uArrowWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowWidth.setObjectName("uArrowWidth")
        self.uArrowSizeLayout.addWidget(self.uArrowWidth)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowSizeLayout.addItem(spacerItem)
        self.uArrowFormatLayout.addLayout(self.uArrowSizeLayout)
        self.uArrowFormatLayout2 = QtWidgets.QHBoxLayout()
        self.uArrowFormatLayout2.setObjectName("uArrowFormatLayout2")
        self.uArrowColorLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowColorLabel.sizePolicy().hasHeightForWidth())
        self.uArrowColorLabel.setSizePolicy(sizePolicy)
        self.uArrowColorLabel.setObjectName("uArrowColorLabel")
        self.uArrowFormatLayout2.addWidget(self.uArrowColorLabel)
        self.uArrowColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowColor.setObjectName("uArrowColor")
        self.uArrowFormatLayout2.addWidget(self.uArrowColor)
        self.uArrowHeadColorLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadColorLabel.setObjectName("uArrowHeadColorLabel")
        self.uArrowFormatLayout2.addWidget(self.uArrowHeadColorLabel)
        self.uFillHead = QtWidgets.QCheckBox(self.uArrowFormatGroup)
        self.uFillHead.setText("")
        self.uFillHead.setObjectName("uFillHead")
        self.uArrowFormatLayout2.addWidget(self.uFillHead)
        self.uArrowHeadColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowHeadColor.setObjectName("uArrowHeadColor")
        self.uArrowFormatLayout2.addWidget(self.uArrowHeadColor)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowFormatLayout2.addItem(spacerItem1)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatLayout2)
        self.uArrowFormatLayout3 = QtWidgets.QHBoxLayout()
        self.uArrowFormatLayout3.setObjectName("uArrowFormatLayout3")
        self.uArrowHeadShapeFrontLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeFrontLabel.setEnabled(False)
        self.uArrowHeadShapeFrontLabel.setObjectName("uArrowHeadShapeFrontLabel")
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeFrontLabel)
        self.uArrowHeadShapeFront = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeFront.setEnabled(False)
        self.uArrowHeadShapeFront.setMinimum(-3.0)
        self.uArrowHeadShapeFront.setMaximum(3.0)
        self.uArrowHeadShapeFront.setSingleStep(0.1)
        self.uArrowHeadShapeFront.setObjectName("uArrowHeadShapeFront")
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeFront)
        self.uArrowHeadShapeBackLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeBackLabel.setEnabled(False)
        self.uArrowHeadShapeBackLabel.setObjectName("uArrowHeadShapeBackLabel")
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeBackLabel)
        self.uArrowHeadShapeBack = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeBack.setEnabled(False)
        self.uArrowHeadShapeBack.setMinimum(-3.0)
        self.uArrowHeadShapeBack.setMaximum(3.0)
        self.uArrowHeadShapeBack.setSingleStep(0.1)
        self.uArrowHeadShapeBack.setObjectName("uArrowHeadShapeBack")
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeBack)
        self.uArrowHeadShapeCentreLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeCentreLabel.setEnabled(False)
        self.uArrowHeadShapeCentreLabel.setObjectName("uArrowHeadShapeCentreLabel")
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeCentreLabel)
        self.uArrowHeadShapeCentre = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeCentre.setEnabled(False)
        self.uArrowHeadShapeCentre.setMinimum(-3.0)
        self.uArrowHeadShapeCentre.setMaximum(3.0)
        self.uArrowHeadShapeCentre.setSingleStep(0.1)
        self.uArrowHeadShapeCentre.setObjectName("uArrowHeadShapeCentre")
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeCentre)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowFormatLayout3.addItem(spacerItem2)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatLayout3)
        self.verticalLayout.addWidget(self.uArrowFormatGroup)
        self.verticalLayout_4.addWidget(self.uTabManager)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uOutputUnitLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uOutputUnitLabel.setObjectName("uOutputUnitLabel")
        self.horizontalLayout_3.addWidget(self.uOutputUnitLabel)
        self.uOutputUnits = QtWidgets.QPushButton(VectorFieldRendererWidget)
        self.uOutputUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uOutputUnits.setObjectName("uOutputUnits")
        self.horizontalLayout_3.addWidget(self.uOutputUnits)
        self.uArrowBaseSizeLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uArrowBaseSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowBaseSizeLabel.setObjectName("uArrowBaseSizeLabel")
        self.horizontalLayout_3.addWidget(self.uArrowBaseSizeLabel)
        self.uArrowBaseSize = QtWidgets.QDoubleSpinBox(VectorFieldRendererWidget)
        self.uArrowBaseSize.setObjectName("uArrowBaseSize")
        self.horizontalLayout_3.addWidget(self.uArrowBaseSize)
        self.uBaseBorderColorLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uBaseBorderColorLabel.setObjectName("uBaseBorderColorLabel")
        self.horizontalLayout_3.addWidget(self.uBaseBorderColorLabel)
        self.uBaseBorderColor = gui.QgsColorButton(VectorFieldRendererWidget)
        self.uBaseBorderColor.setObjectName("uBaseBorderColor")
        self.horizontalLayout_3.addWidget(self.uBaseBorderColor)
        self.uBaseColorLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uBaseColorLabel.setObjectName("uBaseColorLabel")
        self.horizontalLayout_3.addWidget(self.uBaseColorLabel)
        self.uFillBase = QtWidgets.QCheckBox(VectorFieldRendererWidget)
        self.uFillBase.setText("")
        self.uFillBase.setObjectName("uFillBase")
        self.horizontalLayout_3.addWidget(self.uFillBase)
        self.uBaseColor = gui.QgsColorButton(VectorFieldRendererWidget)
        self.uBaseColor.setObjectName("uBaseColor")
        self.horizontalLayout_3.addWidget(self.uBaseColor)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 9, 9, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uArrowScaleLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uArrowScaleLabel.setObjectName("uArrowScaleLabel")
        self.horizontalLayout_4.addWidget(self.uArrowScaleLabel)
        self.uArrowScale = QtWidgets.QLineEdit(VectorFieldRendererWidget)
        self.uArrowScale.setObjectName("uArrowScale")
        self.horizontalLayout_4.addWidget(self.uArrowScale)
        self.uScaleUnits = QtWidgets.QPushButton(VectorFieldRendererWidget)
        self.uScaleUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uScaleUnits.setObjectName("uScaleUnits")
        self.horizontalLayout_4.addWidget(self.uScaleUnits)
        self.uScaleGroupLabel = QtWidgets.QLabel(VectorFieldRendererWidget)
        self.uScaleGroupLabel.setObjectName("uScaleGroupLabel")
        self.horizontalLayout_4.addWidget(self.uScaleGroupLabel)
        self.uScaleGroup = QtWidgets.QLineEdit(VectorFieldRendererWidget)
        self.uScaleGroup.setObjectName("uScaleGroup")
        self.horizontalLayout_4.addWidget(self.uScaleGroup)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.uOutputUnitLabel.setBuddy(self.uOutputUnits)
        self.uArrowBaseSizeLabel.setBuddy(self.uArrowBaseSize)
        self.uBaseBorderColorLabel.setBuddy(self.uBaseBorderColor)
        self.uBaseColorLabel.setBuddy(self.uFillBase)
        self.uArrowScaleLabel.setBuddy(self.uArrowScale)
        self.uScaleGroupLabel.setBuddy(self.uScaleGroup)

        self.retranslateUi(VectorFieldRendererWidget)
        QtCore.QMetaObject.connectSlotsByName(VectorFieldRendererWidget)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeCartesian, self.uFieldTypePolar)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypePolar, self.uFieldTypeHeight)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeHeight, self.uFieldTypeNone)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeNone, self.uXField)
        VectorFieldRendererWidget.setTabOrder(self.uXField, self.uYField)
        VectorFieldRendererWidget.setTabOrder(self.uYField, self.uAngleOrientationEast)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationEast, self.uAngleOrientationNorth)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationNorth, self.uAngleUnitsDegrees)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsDegrees, self.uAngleUnitsRadians)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsRadians, self.uArrowHeadSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadSize, self.uArrowHeadMaxSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadMaxSize, self.uHeadWidth)
        VectorFieldRendererWidget.setTabOrder(self.uHeadWidth, self.uArrowWidth)
        VectorFieldRendererWidget.setTabOrder(self.uArrowWidth, self.uArrowColor)
        VectorFieldRendererWidget.setTabOrder(self.uArrowColor, self.uFillHead)
        VectorFieldRendererWidget.setTabOrder(self.uFillHead, self.uArrowHeadColor)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadColor, self.uArrowHeadShapeFront)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadShapeFront, self.uArrowHeadShapeBack)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadShapeBack, self.uArrowHeadShapeCentre)
        VectorFieldRendererWidget.setTabOrder(self.uArrowHeadShapeCentre, self.uOutputUnits)
        VectorFieldRendererWidget.setTabOrder(self.uOutputUnits, self.uArrowBaseSize)
        VectorFieldRendererWidget.setTabOrder(self.uArrowBaseSize, self.uBaseBorderColor)
        VectorFieldRendererWidget.setTabOrder(self.uBaseBorderColor, self.uFillBase)
        VectorFieldRendererWidget.setTabOrder(self.uFillBase, self.uBaseColor)
        VectorFieldRendererWidget.setTabOrder(self.uBaseColor, self.uArrowScale)
        VectorFieldRendererWidget.setTabOrder(self.uArrowScale, self.uScaleUnits)
        VectorFieldRendererWidget.setTabOrder(self.uScaleUnits, self.uScaleGroup)

    def retranslateUi(self, VectorFieldRendererWidget):
        _translate = QtCore.QCoreApplication.translate
        VectorFieldRendererWidget.setWindowTitle(_translate("VectorFieldRendererWidget", "Form"))
        self.uVectorFieldTypeGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Vector field type"))
        self.uFieldTypeCartesian.setText(_translate("VectorFieldRendererWidget", "Cartesian (XY) field"))
        self.uFieldTypePolar.setText(_translate("VectorFieldRendererWidget", "Polar (length,angle) field"))
        self.uFieldTypeHeight.setText(_translate("VectorFieldRendererWidget", "Height only"))
        self.uFieldTypeNone.setText(_translate("VectorFieldRendererWidget", "None"))
        self.uXFieldLabel.setText(_translate("VectorFieldRendererWidget", "X attribute"))
        self.uYFieldLabel.setText(_translate("VectorFieldRendererWidget", "Y attribute"))
        self.uOrientationGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle orientation"))
        self.uAngleOrientationEast.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation"))
        self.uAngleOrientationEast.setText(_translate("VectorFieldRendererWidget", "North from east"))
        self.uAngleOrientationNorth.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation"))
        self.uAngleOrientationNorth.setText(_translate("VectorFieldRendererWidget", "East from north"))
        self.uAngleUnitsGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle units"))
        self.uAngleUnitsDegrees.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units"))
        self.uAngleUnitsDegrees.setText(_translate("VectorFieldRendererWidget", "Degrees"))
        self.uAngleUnitsRadians.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units"))
        self.uAngleUnitsRadians.setText(_translate("VectorFieldRendererWidget", "Radians"))
        self.uArrowFormatGroup.setTitle(_translate("VectorFieldRendererWidget", "Arrow format"))
        self.uArrowHeadSizeLabel.setText(_translate("VectorFieldRendererWidget", "Size: Head (relative)"))
        self.uArrowHeadSize.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uArrowHeadMaxSizeLabel.setText(_translate("VectorFieldRendererWidget", "Head (max)"))
        self.uArrowHeadMaxSize.setToolTip(_translate("VectorFieldRendererWidget", "Maximum arrow head size"))
        self.uHeadWidthLabel.setText(_translate("VectorFieldRendererWidget", "Head border width"))
        self.uHeadWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft"))
        self.uArrowWidthLabel.setText(_translate("VectorFieldRendererWidget", " Shaft width"))
        self.uArrowWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft"))
        self.uArrowColorLabel.setText(_translate("VectorFieldRendererWidget", "Colour: Head border/shaft"))
        self.uArrowColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour"))
        self.uArrowColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uArrowHeadColorLabel.setText(_translate("VectorFieldRendererWidget", "Head fill?"))
        self.uArrowHeadColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour"))
        self.uArrowHeadColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uArrowHeadShapeFrontLabel.setText(_translate("VectorFieldRendererWidget", "Arrow shape (relative x coords): front"))
        self.uArrowHeadShapeFront.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uArrowHeadShapeBackLabel.setText(_translate("VectorFieldRendererWidget", "back outside"))
        self.uArrowHeadShapeBack.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uArrowHeadShapeCentreLabel.setText(_translate("VectorFieldRendererWidget", "back centre"))
        self.uArrowHeadShapeCentre.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length"))
        self.uOutputUnitLabel.setText(_translate("VectorFieldRendererWidget", "Symbol units"))
        self.uOutputUnits.setText(_translate("VectorFieldRendererWidget", "Millimeter"))
        self.uArrowBaseSizeLabel.setText(_translate("VectorFieldRendererWidget", "Base size"))
        self.uArrowBaseSize.setToolTip(_translate("VectorFieldRendererWidget", "Size of the arrow base symbol"))
        self.uBaseBorderColorLabel.setText(_translate("VectorFieldRendererWidget", "Colours: Border"))
        self.uBaseBorderColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base border colour"))
        self.uBaseBorderColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uBaseColorLabel.setText(_translate("VectorFieldRendererWidget", "Fill?"))
        self.uBaseColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base symbol colour"))
        self.uBaseColor.setText(_translate("VectorFieldRendererWidget", "change"))
        self.uArrowScaleLabel.setText(_translate("VectorFieldRendererWidget", "Scale:  "))
        self.uScaleUnits.setText(_translate("VectorFieldRendererWidget", "Millimeter"))
        self.uScaleGroupLabel.setText(_translate("VectorFieldRendererWidget", "    Scale group"))

from qgis import gui
