# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\OSGeo4W\apps\qgis-dev\python\plugins\VectorFieldRenderer\Ui_VectorScaleBoxOptionsDialog.ui'
#
# Created: Mon Feb 15 14:44:05 2010
#      by: PyQt4 UI code generator 4.5.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_VectorScaleBoxOptionsDialog(object):
    def setupUi(self, VectorScaleBoxOptionsDialog):
        VectorScaleBoxOptionsDialog.setObjectName("VectorScaleBoxOptionsDialog")
        VectorScaleBoxOptionsDialog.resize(399, 274)
        self.uMainLayout = QtGui.QVBoxLayout(VectorScaleBoxOptionsDialog)
        self.uMainLayout.setObjectName("uMainLayout")
        self.uLocationGroup = QtGui.QGroupBox(VectorScaleBoxOptionsDialog)
        self.uLocationGroup.setObjectName("uLocationGroup")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uLocationGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uLocationLayout = QtGui.QVBoxLayout()
        self.uLocationLayout.setObjectName("uLocationLayout")
        self.uPositionLayout_2 = QtGui.QHBoxLayout()
        self.uPositionLayout_2.setObjectName("uPositionLayout_2")
        self.uPositionLabel = QtGui.QLabel(self.uLocationGroup)
        self.uPositionLabel.setObjectName("uPositionLabel")
        self.uPositionLayout_2.addWidget(self.uPositionLabel)
        self.uRadioTL = QtGui.QRadioButton(self.uLocationGroup)
        self.uRadioTL.setObjectName("uRadioTL")
        self.uPositionLayout_2.addWidget(self.uRadioTL)
        self.uRadioTR = QtGui.QRadioButton(self.uLocationGroup)
        self.uRadioTR.setObjectName("uRadioTR")
        self.uPositionLayout_2.addWidget(self.uRadioTR)
        self.uRadioBL = QtGui.QRadioButton(self.uLocationGroup)
        self.uRadioBL.setObjectName("uRadioBL")
        self.uPositionLayout_2.addWidget(self.uRadioBL)
        self.uRadioBR = QtGui.QRadioButton(self.uLocationGroup)
        self.uRadioBR.setChecked(True)
        self.uRadioBR.setObjectName("uRadioBR")
        self.uPositionLayout_2.addWidget(self.uRadioBR)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uPositionLayout_2.addItem(spacerItem)
        self.uLocationLayout.addLayout(self.uPositionLayout_2)
        self.verticalLayout_2.addLayout(self.uLocationLayout)
        self.uPositionLayout = QtGui.QHBoxLayout()
        self.uPositionLayout.setObjectName("uPositionLayout")
        self.uOffsetXLabel = QtGui.QLabel(self.uLocationGroup)
        self.uOffsetXLabel.setObjectName("uOffsetXLabel")
        self.uPositionLayout.addWidget(self.uOffsetXLabel)
        self.uOffsetX = QtGui.QSpinBox(self.uLocationGroup)
        self.uOffsetX.setMaximum(300)
        self.uOffsetX.setObjectName("uOffsetX")
        self.uPositionLayout.addWidget(self.uOffsetX)
        self.uOffsetYLabel = QtGui.QLabel(self.uLocationGroup)
        self.uOffsetYLabel.setObjectName("uOffsetYLabel")
        self.uPositionLayout.addWidget(self.uOffsetYLabel)
        self.uOffsetY = QtGui.QSpinBox(self.uLocationGroup)
        self.uOffsetY.setMaximum(300)
        self.uOffsetY.setObjectName("uOffsetY")
        self.uPositionLayout.addWidget(self.uOffsetY)
        self.uArrowSizeLabel = QtGui.QLabel(self.uLocationGroup)
        self.uArrowSizeLabel.setObjectName("uArrowSizeLabel")
        self.uPositionLayout.addWidget(self.uArrowSizeLabel)
        self.uArrowSizePercent = QtGui.QSpinBox(self.uLocationGroup)
        self.uArrowSizePercent.setMaximum(30)
        self.uArrowSizePercent.setObjectName("uArrowSizePercent")
        self.uPositionLayout.addWidget(self.uArrowSizePercent)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uPositionLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.uPositionLayout)
        self.uMainLayout.addWidget(self.uLocationGroup)
        self.uBoxGroup = QtGui.QGroupBox(VectorScaleBoxOptionsDialog)
        self.uBoxGroup.setObjectName("uBoxGroup")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.uBoxGroup)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.uShowBoxLabel = QtGui.QLabel(self.uBoxGroup)
        self.uShowBoxLabel.setObjectName("uShowBoxLabel")
        self.horizontalLayout_6.addWidget(self.uShowBoxLabel)
        self.uShowBox = QtGui.QCheckBox(self.uBoxGroup)
        self.uShowBox.setObjectName("uShowBox")
        self.horizontalLayout_6.addWidget(self.uShowBox)
        self.uFillBoxLabel = QtGui.QLabel(self.uBoxGroup)
        self.uFillBoxLabel.setObjectName("uFillBoxLabel")
        self.horizontalLayout_6.addWidget(self.uFillBoxLabel)
        self.uFillBox = QtGui.QCheckBox(self.uBoxGroup)
        self.uFillBox.setObjectName("uFillBox")
        self.horizontalLayout_6.addWidget(self.uFillBox)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.uPenColor = QgsColorButtonV2(self.uBoxGroup)
        self.uPenColor.setObjectName("uPenColor")
        self.horizontalLayout_6.addWidget(self.uPenColor)
        self.uBrushColor = QgsColorButtonV2(self.uBoxGroup)
        self.uBrushColor.setObjectName("uBrushColor")
        self.horizontalLayout_6.addWidget(self.uBrushColor)
        self.uMainLayout.addWidget(self.uBoxGroup)
        self.uTextGroup = QtGui.QGroupBox(VectorScaleBoxOptionsDialog)
        self.uTextGroup.setObjectName("uTextGroup")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.uTextGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uTitleLabel = QtGui.QLabel(self.uTextGroup)
        self.uTitleLabel.setObjectName("uTitleLabel")
        self.horizontalLayout_3.addWidget(self.uTitleLabel)
        self.uTitle = QtGui.QLineEdit(self.uTextGroup)
        self.uTitle.setObjectName("uTitle")
        self.horizontalLayout_3.addWidget(self.uTitle)
        self.uTitleFont = QtGui.QPushButton(self.uTextGroup)
        self.uTitleFont.setObjectName("uTitleFont")
        self.horizontalLayout_3.addWidget(self.uTitleFont)
        self.uScaleFont = QtGui.QPushButton(self.uTextGroup)
        self.uScaleFont.setObjectName("uScaleFont")
        self.horizontalLayout_3.addWidget(self.uScaleFont)
        self.uMainLayout.addWidget(self.uTextGroup)
        self.uButtonBox = QtGui.QDialogButtonBox(VectorScaleBoxOptionsDialog)
        self.uButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.uButtonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.uButtonBox.setObjectName("uButtonBox")
        self.uMainLayout.addWidget(self.uButtonBox)
        self.uPositionLabel.setBuddy(self.uRadioTL)
        self.uOffsetXLabel.setBuddy(self.uOffsetX)
        self.uOffsetYLabel.setBuddy(self.uOffsetY)
        self.uArrowSizeLabel.setBuddy(self.uArrowSizePercent)
        self.uShowBoxLabel.setBuddy(self.uShowBox)
        self.uFillBoxLabel.setBuddy(self.uFillBox)
        self.uTitleLabel.setBuddy(self.uTitle)

        self.retranslateUi(VectorScaleBoxOptionsDialog)
        QtCore.QObject.connect(self.uButtonBox, QtCore.SIGNAL("accepted()"), VectorScaleBoxOptionsDialog.accept)
        QtCore.QObject.connect(self.uButtonBox, QtCore.SIGNAL("rejected()"), VectorScaleBoxOptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(VectorScaleBoxOptionsDialog)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioTL, self.uRadioTR)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioTR, self.uRadioBL)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioBL, self.uRadioBR)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioBR, self.uOffsetX)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uOffsetX, self.uOffsetY)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uOffsetY, self.uArrowSizePercent)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uArrowSizePercent, self.uShowBox)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uShowBox, self.uFillBox)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uFillBox, self.uPenColor)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uPenColor, self.uBrushColor)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uBrushColor, self.uTitle)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uTitle, self.uTitleFont)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uTitleFont, self.uScaleFont)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uScaleFont, self.uButtonBox)

    def retranslateUi(self, VectorScaleBoxOptionsDialog):
        VectorScaleBoxOptionsDialog.setWindowTitle(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Vector scale box options", None, QtGui.QApplication.UnicodeUTF8))
        self.uLocationGroup.setTitle(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Location", None, QtGui.QApplication.UnicodeUTF8))
        self.uPositionLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.uRadioTL.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Top left", None, QtGui.QApplication.UnicodeUTF8))
        self.uRadioTR.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Top right", None, QtGui.QApplication.UnicodeUTF8))
        self.uRadioBL.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Bottom left", None, QtGui.QApplication.UnicodeUTF8))
        self.uRadioBR.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Bottom right", None, QtGui.QApplication.UnicodeUTF8))
        self.uOffsetXLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Offset: X", None, QtGui.QApplication.UnicodeUTF8))
        self.uOffsetYLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "   Y", None, QtGui.QApplication.UnicodeUTF8))
        self.uArrowSizeLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "     Approx arrow size (%)", None, QtGui.QApplication.UnicodeUTF8))
        self.uBoxGroup.setTitle(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Box", None, QtGui.QApplication.UnicodeUTF8))
        self.uShowBoxLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Draw box?", None, QtGui.QApplication.UnicodeUTF8))
        self.uFillBoxLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Fill box?", None, QtGui.QApplication.UnicodeUTF8))
        self.uPenColor.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Border color", None, QtGui.QApplication.UnicodeUTF8))
        self.uBrushColor.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Fill color", None, QtGui.QApplication.UnicodeUTF8))
        self.uTextGroup.setTitle(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Text", None, QtGui.QApplication.UnicodeUTF8))
        self.uTitleLabel.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Title: ", None, QtGui.QApplication.UnicodeUTF8))
        self.uTitleFont.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Title font", None, QtGui.QApplication.UnicodeUTF8))
        self.uScaleFont.setText(QtGui.QApplication.translate("VectorScaleBoxOptionsDialog", "Scale font", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsColorButtonV2
