# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VectorFieldRendererWidget.ui'
#
# Created: Wed Sep  7 14:16:59 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_VectorFieldRendererWidget(object):
    def setupUi(self, VectorFieldRendererWidget):
        VectorFieldRendererWidget.setObjectName(_fromUtf8("VectorFieldRendererWidget"))
        VectorFieldRendererWidget.resize(778, 510)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VectorFieldRendererWidget.sizePolicy().hasHeightForWidth())
        VectorFieldRendererWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtGui.QVBoxLayout(VectorFieldRendererWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.uCrashWarning = QtGui.QLabel(VectorFieldRendererWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.uCrashWarning.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.uCrashWarning.setFont(font)
        self.uCrashWarning.setObjectName(_fromUtf8("uCrashWarning"))
        self.verticalLayout_4.addWidget(self.uCrashWarning)
        self.uTabManager = QtGui.QTabWidget(VectorFieldRendererWidget)
        self.uTabManager.setObjectName(_fromUtf8("uTabManager"))
        self.uVectorTab = QtGui.QWidget()
        self.uVectorTab.setObjectName(_fromUtf8("uVectorTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.uVectorTab)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.uVectorFieldTypeGroupBox = QtGui.QGroupBox(self.uVectorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uVectorFieldTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uVectorFieldTypeGroupBox.setSizePolicy(sizePolicy)
        self.uVectorFieldTypeGroupBox.setObjectName(_fromUtf8("uVectorFieldTypeGroupBox"))
        self.uFieldTypeLayout = QtGui.QHBoxLayout(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeLayout.setMargin(0)
        self.uFieldTypeLayout.setObjectName(_fromUtf8("uFieldTypeLayout"))
        self.uFieldTypeCartesian = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeCartesian.setChecked(True)
        self.uFieldTypeCartesian.setObjectName(_fromUtf8("uFieldTypeCartesian"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypeCartesian)
        self.uFieldTypePolar = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypePolar.setObjectName(_fromUtf8("uFieldTypePolar"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypePolar)
        self.uFieldTypeHeight = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeHeight.setObjectName(_fromUtf8("uFieldTypeHeight"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypeHeight)
        self.uFieldTypeNone = QtGui.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeNone.setObjectName(_fromUtf8("uFieldTypeNone"))
        self.uFieldTypeLayout.addWidget(self.uFieldTypeNone)
        self.verticalLayout.addWidget(self.uVectorFieldTypeGroupBox)
        self.uVectorFieldGrid = QtGui.QGridLayout()
        self.uVectorFieldGrid.setObjectName(_fromUtf8("uVectorFieldGrid"))
        self.uXFieldLabel = QtGui.QLabel(self.uVectorTab)
        self.uXFieldLabel.setObjectName(_fromUtf8("uXFieldLabel"))
        self.uVectorFieldGrid.addWidget(self.uXFieldLabel, 0, 0, 1, 1)
        self.uYFieldLabel = QtGui.QLabel(self.uVectorTab)
        self.uYFieldLabel.setObjectName(_fromUtf8("uYFieldLabel"))
        self.uVectorFieldGrid.addWidget(self.uYFieldLabel, 1, 0, 1, 1)
        self.uYField = QtGui.QComboBox(self.uVectorTab)
        self.uYField.setObjectName(_fromUtf8("uYField"))
        self.uVectorFieldGrid.addWidget(self.uYField, 1, 1, 1, 1)
        self.uXField = QtGui.QComboBox(self.uVectorTab)
        self.uXField.setObjectName(_fromUtf8("uXField"))
        self.uVectorFieldGrid.addWidget(self.uXField, 0, 1, 1, 1)
        self.uVectorFieldGrid.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.uVectorFieldGrid)
        self.uAngleFormatLayout = QtGui.QHBoxLayout()
        self.uAngleFormatLayout.setContentsMargins(0, -1, 0, -1)
        self.uAngleFormatLayout.setObjectName(_fromUtf8("uAngleFormatLayout"))
        self.uOrientationGroupBox = QtGui.QGroupBox(self.uVectorTab)
        self.uOrientationGroupBox.setEnabled(True)
        self.uOrientationGroupBox.setObjectName(_fromUtf8("uOrientationGroupBox"))
        self.uOrientationLayout = QtGui.QHBoxLayout(self.uOrientationGroupBox)
        self.uOrientationLayout.setSpacing(6)
        self.uOrientationLayout.setMargin(9)
        self.uOrientationLayout.setObjectName(_fromUtf8("uOrientationLayout"))
        self.uAngleOrientationEast = QtGui.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationEast.setChecked(True)
        self.uAngleOrientationEast.setObjectName(_fromUtf8("uAngleOrientationEast"))
        self.uOrientationLayout.addWidget(self.uAngleOrientationEast)
        self.uAngleOrientationNorth = QtGui.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationNorth.setObjectName(_fromUtf8("uAngleOrientationNorth"))
        self.uOrientationLayout.addWidget(self.uAngleOrientationNorth)
        self.uAngleFormatLayout.addWidget(self.uOrientationGroupBox)
        self.uAngleUnitsGroupBox = QtGui.QGroupBox(self.uVectorTab)
        self.uAngleUnitsGroupBox.setEnabled(True)
        self.uAngleUnitsGroupBox.setObjectName(_fromUtf8("uAngleUnitsGroupBox"))
        self.uAngleUnitsLayout = QtGui.QHBoxLayout(self.uAngleUnitsGroupBox)
        self.uAngleUnitsLayout.setContentsMargins(-1, 9, -1, 9)
        self.uAngleUnitsLayout.setObjectName(_fromUtf8("uAngleUnitsLayout"))
        self.uAngleUnitsDegrees = QtGui.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsDegrees.setChecked(True)
        self.uAngleUnitsDegrees.setObjectName(_fromUtf8("uAngleUnitsDegrees"))
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsDegrees)
        self.uAngleUnitsRadians = QtGui.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsRadians.setEnabled(True)
        self.uAngleUnitsRadians.setObjectName(_fromUtf8("uAngleUnitsRadians"))
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsRadians)
        self.uAngleFormatLayout.addWidget(self.uAngleUnitsGroupBox)
        self.verticalLayout.addLayout(self.uAngleFormatLayout)
        self.uArrowFormatGroup = QtGui.QGroupBox(self.uVectorTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowFormatGroup.sizePolicy().hasHeightForWidth())
        self.uArrowFormatGroup.setSizePolicy(sizePolicy)
        self.uArrowFormatGroup.setObjectName(_fromUtf8("uArrowFormatGroup"))
        self.uArrowFormatLayout = QtGui.QVBoxLayout(self.uArrowFormatGroup)
        self.uArrowFormatLayout.setMargin(0)
        self.uArrowFormatLayout.setObjectName(_fromUtf8("uArrowFormatLayout"))
        self.uArrowSizeLayout = QtGui.QHBoxLayout()
        self.uArrowSizeLayout.setObjectName(_fromUtf8("uArrowSizeLayout"))
        self.uArrowHeadSizeLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadSizeLabel.setObjectName(_fromUtf8("uArrowHeadSizeLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSizeLabel)
        self.uArrowHeadSize = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadSize.setMinimum(-3.0)
        self.uArrowHeadSize.setMaximum(3.0)
        self.uArrowHeadSize.setSingleStep(0.1)
        self.uArrowHeadSize.setObjectName(_fromUtf8("uArrowHeadSize"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadMaxSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadMaxSizeLabel.setObjectName(_fromUtf8("uArrowHeadMaxSizeLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSizeLabel)
        self.uArrowHeadMaxSize = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadMaxSize.setObjectName(_fromUtf8("uArrowHeadMaxSize"))
        self.uArrowSizeLayout.addWidget(self.uArrowHeadMaxSize)
        self.uHeadWidthLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uHeadWidthLabel.setObjectName(_fromUtf8("uHeadWidthLabel"))
        self.uArrowSizeLayout.addWidget(self.uHeadWidthLabel)
        self.uHeadWidth = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uHeadWidth.setObjectName(_fromUtf8("uHeadWidth"))
        self.uArrowSizeLayout.addWidget(self.uHeadWidth)
        self.uArrowWidthLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowWidthLabel.setObjectName(_fromUtf8("uArrowWidthLabel"))
        self.uArrowSizeLayout.addWidget(self.uArrowWidthLabel)
        self.uArrowWidth = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowWidth.setObjectName(_fromUtf8("uArrowWidth"))
        self.uArrowSizeLayout.addWidget(self.uArrowWidth)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowSizeLayout.addItem(spacerItem)
        self.uArrowFormatLayout.addLayout(self.uArrowSizeLayout)
        self.uArrowFormatLayout2 = QtGui.QHBoxLayout()
        self.uArrowFormatLayout2.setObjectName(_fromUtf8("uArrowFormatLayout2"))
        self.uArrowColorLabel = QtGui.QLabel(self.uArrowFormatGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowColorLabel.sizePolicy().hasHeightForWidth())
        self.uArrowColorLabel.setSizePolicy(sizePolicy)
        self.uArrowColorLabel.setObjectName(_fromUtf8("uArrowColorLabel"))
        self.uArrowFormatLayout2.addWidget(self.uArrowColorLabel)
        self.uArrowColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowColor.setObjectName(_fromUtf8("uArrowColor"))
        self.uArrowFormatLayout2.addWidget(self.uArrowColor)
        self.uArrowHeadColorLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadColorLabel.setObjectName(_fromUtf8("uArrowHeadColorLabel"))
        self.uArrowFormatLayout2.addWidget(self.uArrowHeadColorLabel)
        self.uFillHead = QtGui.QCheckBox(self.uArrowFormatGroup)
        self.uFillHead.setText(_fromUtf8(""))
        self.uFillHead.setObjectName(_fromUtf8("uFillHead"))
        self.uArrowFormatLayout2.addWidget(self.uFillHead)
        self.uArrowHeadColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowHeadColor.setObjectName(_fromUtf8("uArrowHeadColor"))
        self.uArrowFormatLayout2.addWidget(self.uArrowHeadColor)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowFormatLayout2.addItem(spacerItem1)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatLayout2)
        self.uArrowFormatLayout3 = QtGui.QHBoxLayout()
        self.uArrowFormatLayout3.setObjectName(_fromUtf8("uArrowFormatLayout3"))
        self.uArrowHeadShapeFrontLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeFrontLabel.setObjectName(_fromUtf8("uArrowHeadShapeFrontLabel"))
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeFrontLabel)
        self.uArrowHeadShapeFront = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeFront.setMinimum(-3.0)
        self.uArrowHeadShapeFront.setMaximum(3.0)
        self.uArrowHeadShapeFront.setSingleStep(0.1)
        self.uArrowHeadShapeFront.setObjectName(_fromUtf8("uArrowHeadShapeFront"))
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeFront)
        self.uArrowHeadShapeBackLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeBackLabel.setObjectName(_fromUtf8("uArrowHeadShapeBackLabel"))
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeBackLabel)
        self.uArrowHeadShapeBack = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeBack.setMinimum(-3.0)
        self.uArrowHeadShapeBack.setMaximum(3.0)
        self.uArrowHeadShapeBack.setSingleStep(0.1)
        self.uArrowHeadShapeBack.setObjectName(_fromUtf8("uArrowHeadShapeBack"))
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeBack)
        self.uArrowHeadShapeCentreLabel = QtGui.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadShapeCentreLabel.setObjectName(_fromUtf8("uArrowHeadShapeCentreLabel"))
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeCentreLabel)
        self.uArrowHeadShapeCentre = QtGui.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadShapeCentre.setMinimum(-3.0)
        self.uArrowHeadShapeCentre.setMaximum(3.0)
        self.uArrowHeadShapeCentre.setSingleStep(0.1)
        self.uArrowHeadShapeCentre.setObjectName(_fromUtf8("uArrowHeadShapeCentre"))
        self.uArrowFormatLayout3.addWidget(self.uArrowHeadShapeCentre)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowFormatLayout3.addItem(spacerItem2)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatLayout3)
        self.verticalLayout.addWidget(self.uArrowFormatGroup)
        self.uTabManager.addTab(self.uVectorTab, _fromUtf8(""))
        self.uEllipseTab = QtGui.QWidget()
        self.uEllipseTab.setObjectName(_fromUtf8("uEllipseTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.uEllipseTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.uErrorEllipseTypeGroupBox = QtGui.QGroupBox(self.uEllipseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uErrorEllipseTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uErrorEllipseTypeGroupBox.setSizePolicy(sizePolicy)
        self.uErrorEllipseTypeGroupBox.setObjectName(_fromUtf8("uErrorEllipseTypeGroupBox"))
        self.uFieldTypeLayout_2 = QtGui.QHBoxLayout(self.uErrorEllipseTypeGroupBox)
        self.uFieldTypeLayout_2.setMargin(0)
        self.uFieldTypeLayout_2.setObjectName(_fromUtf8("uFieldTypeLayout_2"))
        self.uEllipseTypeCovariance = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCovariance.setChecked(False)
        self.uEllipseTypeCovariance.setObjectName(_fromUtf8("uEllipseTypeCovariance"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCovariance)
        self.uEllipseTypeAxes = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeAxes.setObjectName(_fromUtf8("uEllipseTypeAxes"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeAxes)
        self.uEllipseTypeCircular = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCircular.setObjectName(_fromUtf8("uEllipseTypeCircular"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCircular)
        self.uEllipseTypeHeight = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeHeight.setObjectName(_fromUtf8("uEllipseTypeHeight"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeHeight)
        self.uEllipseTypeNone = QtGui.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeNone.setChecked(True)
        self.uEllipseTypeNone.setObjectName(_fromUtf8("uEllipseTypeNone"))
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeNone)
        self.verticalLayout_2.addWidget(self.uErrorEllipseTypeGroupBox)
        self.uVectorFieldGrid_2 = QtGui.QGridLayout()
        self.uVectorFieldGrid_2.setObjectName(_fromUtf8("uVectorFieldGrid_2"))
        self.uCxxFieldLabel = QtGui.QLabel(self.uEllipseTab)
        self.uCxxFieldLabel.setObjectName(_fromUtf8("uCxxFieldLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uCxxFieldLabel, 0, 0, 1, 1)
        self.uCxyFieldLabel = QtGui.QLabel(self.uEllipseTab)
        self.uCxyFieldLabel.setObjectName(_fromUtf8("uCxyFieldLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uCxyFieldLabel, 1, 0, 1, 1)
        self.uCxyField = QtGui.QComboBox(self.uEllipseTab)
        self.uCxyField.setObjectName(_fromUtf8("uCxyField"))
        self.uVectorFieldGrid_2.addWidget(self.uCxyField, 1, 2, 1, 1)
        self.uEllipseScaleLabel = QtGui.QLabel(self.uEllipseTab)
        self.uEllipseScaleLabel.setObjectName(_fromUtf8("uEllipseScaleLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uEllipseScaleLabel, 3, 0, 1, 1)
        self.uArrowScaleLayout_2 = QtGui.QHBoxLayout()
        self.uArrowScaleLayout_2.setObjectName(_fromUtf8("uArrowScaleLayout_2"))
        self.uEllipseScale = QtGui.QLineEdit(self.uEllipseTab)
        self.uEllipseScale.setObjectName(_fromUtf8("uEllipseScale"))
        self.uArrowScaleLayout_2.addWidget(self.uEllipseScale)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uArrowScaleLayout_2.addItem(spacerItem3)
        self.uVectorFieldGrid_2.addLayout(self.uArrowScaleLayout_2, 3, 2, 1, 1)
        self.uCxxField = QtGui.QComboBox(self.uEllipseTab)
        self.uCxxField.setObjectName(_fromUtf8("uCxxField"))
        self.uVectorFieldGrid_2.addWidget(self.uCxxField, 0, 2, 1, 1)
        self.uCyyFieldLabel = QtGui.QLabel(self.uEllipseTab)
        self.uCyyFieldLabel.setObjectName(_fromUtf8("uCyyFieldLabel"))
        self.uVectorFieldGrid_2.addWidget(self.uCyyFieldLabel, 2, 0, 1, 1)
        self.uCyyField = QtGui.QComboBox(self.uEllipseTab)
        self.uCyyField.setObjectName(_fromUtf8("uCyyField"))
        self.uVectorFieldGrid_2.addWidget(self.uCyyField, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.uVectorFieldGrid_2)
        self.uAxisAngleFormatLayout = QtGui.QHBoxLayout()
        self.uAxisAngleFormatLayout.setContentsMargins(-1, 0, -1, -1)
        self.uAxisAngleFormatLayout.setObjectName(_fromUtf8("uAxisAngleFormatLayout"))
        self.uAxisOrientationGroupBox = QtGui.QGroupBox(self.uEllipseTab)
        self.uAxisOrientationGroupBox.setEnabled(True)
        self.uAxisOrientationGroupBox.setObjectName(_fromUtf8("uAxisOrientationGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.uAxisOrientationGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.uEllipseOrientationEast = QtGui.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationEast.setChecked(True)
        self.uEllipseOrientationEast.setObjectName(_fromUtf8("uEllipseOrientationEast"))
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationEast)
        self.uEllipseOrientationNorth = QtGui.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationNorth.setObjectName(_fromUtf8("uEllipseOrientationNorth"))
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationNorth)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisOrientationGroupBox)
        self.uAxisAngleUnitsGroupBox = QtGui.QGroupBox(self.uEllipseTab)
        self.uAxisAngleUnitsGroupBox.setEnabled(True)
        self.uAxisAngleUnitsGroupBox.setObjectName(_fromUtf8("uAxisAngleUnitsGroupBox"))
        self.uAngleUnitsLayout_2 = QtGui.QHBoxLayout(self.uAxisAngleUnitsGroupBox)
        self.uAngleUnitsLayout_2.setContentsMargins(-1, 9, -1, 9)
        self.uAngleUnitsLayout_2.setObjectName(_fromUtf8("uAngleUnitsLayout_2"))
        self.uEllipseAngleUnitsDegrees = QtGui.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsDegrees.setChecked(True)
        self.uEllipseAngleUnitsDegrees.setObjectName(_fromUtf8("uEllipseAngleUnitsDegrees"))
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsDegrees)
        self.uEllipseAngleUnitsRadians = QtGui.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsRadians.setEnabled(True)
        self.uEllipseAngleUnitsRadians.setObjectName(_fromUtf8("uEllipseAngleUnitsRadians"))
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsRadians)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisAngleUnitsGroupBox)
        self.verticalLayout_2.addLayout(self.uAxisAngleFormatLayout)
        self.uEllipseFormatGroup = QtGui.QGroupBox(self.uEllipseTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uEllipseFormatGroup.sizePolicy().hasHeightForWidth())
        self.uEllipseFormatGroup.setSizePolicy(sizePolicy)
        self.uEllipseFormatGroup.setObjectName(_fromUtf8("uEllipseFormatGroup"))
        self.uArrowFormatLayout_2 = QtGui.QVBoxLayout(self.uEllipseFormatGroup)
        self.uArrowFormatLayout_2.setSpacing(6)
        self.uArrowFormatLayout_2.setMargin(0)
        self.uArrowFormatLayout_2.setObjectName(_fromUtf8("uArrowFormatLayout_2"))
        self.uEllipseFormatLayout1 = QtGui.QHBoxLayout()
        self.uEllipseFormatLayout1.setObjectName(_fromUtf8("uEllipseFormatLayout1"))
        self.uEllipseWidthLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uEllipseWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uEllipseWidthLabel.setObjectName(_fromUtf8("uEllipseWidthLabel"))
        self.uEllipseFormatLayout1.addWidget(self.uEllipseWidthLabel)
        self.uEllipseBorderWidth = QtGui.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseBorderWidth.setObjectName(_fromUtf8("uEllipseBorderWidth"))
        self.uEllipseFormatLayout1.addWidget(self.uEllipseBorderWidth)
        self.uTickSizeLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uTickSizeLabel.setObjectName(_fromUtf8("uTickSizeLabel"))
        self.uEllipseFormatLayout1.addWidget(self.uTickSizeLabel)
        self.uEllipseTickSize = QtGui.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseTickSize.setObjectName(_fromUtf8("uEllipseTickSize"))
        self.uEllipseFormatLayout1.addWidget(self.uEllipseTickSize)
        self.uDrawEllipseLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uDrawEllipseLabel.setObjectName(_fromUtf8("uDrawEllipseLabel"))
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseLabel)
        self.uDrawEllipse = QtGui.QCheckBox(self.uEllipseFormatGroup)
        self.uDrawEllipse.setText(_fromUtf8(""))
        self.uDrawEllipse.setObjectName(_fromUtf8("uDrawEllipse"))
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipse)
        self.uDrawEllipseAxesLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uDrawEllipseAxesLabel.setObjectName(_fromUtf8("uDrawEllipseAxesLabel"))
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseAxesLabel)
        self.uDrawEllipseAxes = QtGui.QCheckBox(self.uEllipseFormatGroup)
        self.uDrawEllipseAxes.setText(_fromUtf8(""))
        self.uDrawEllipseAxes.setObjectName(_fromUtf8("uDrawEllipseAxes"))
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseAxes)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uEllipseFormatLayout1.addItem(spacerItem4)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseFormatLayout1)
        self.uEllipseFormatLayout2 = QtGui.QHBoxLayout()
        self.uEllipseFormatLayout2.setContentsMargins(-1, 6, -1, -1)
        self.uEllipseFormatLayout2.setObjectName(_fromUtf8("uEllipseFormatLayout2"))
        self.uEllipseColorLayoutLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uEllipseColorLayoutLabel.setObjectName(_fromUtf8("uEllipseColorLayoutLabel"))
        self.uEllipseFormatLayout2.addWidget(self.uEllipseColorLayoutLabel)
        self.uEllipseBorderColor = gui.QgsColorButton(self.uEllipseFormatGroup)
        self.uEllipseBorderColor.setObjectName(_fromUtf8("uEllipseBorderColor"))
        self.uEllipseFormatLayout2.addWidget(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel = QtGui.QLabel(self.uEllipseFormatGroup)
        self.uEllipseFillColorLabel.setObjectName(_fromUtf8("uEllipseFillColorLabel"))
        self.uEllipseFormatLayout2.addWidget(self.uEllipseFillColorLabel)
        self.uFillEllipse = QtGui.QCheckBox(self.uEllipseFormatGroup)
        self.uFillEllipse.setText(_fromUtf8(""))
        self.uFillEllipse.setObjectName(_fromUtf8("uFillEllipse"))
        self.uEllipseFormatLayout2.addWidget(self.uFillEllipse)
        self.uEllipseFillColor = gui.QgsColorButton(self.uEllipseFormatGroup)
        self.uEllipseFillColor.setObjectName(_fromUtf8("uEllipseFillColor"))
        self.uEllipseFormatLayout2.addWidget(self.uEllipseFillColor)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.uEllipseFormatLayout2.addItem(spacerItem5)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseFormatLayout2)
        self.verticalLayout_2.addWidget(self.uEllipseFormatGroup)
        self.uTabManager.addTab(self.uEllipseTab, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.uTabManager)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.uOutputUnitLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uOutputUnitLabel.setObjectName(_fromUtf8("uOutputUnitLabel"))
        self.horizontalLayout_3.addWidget(self.uOutputUnitLabel)
        self.uOutputUnits = QtGui.QPushButton(VectorFieldRendererWidget)
        self.uOutputUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uOutputUnits.setObjectName(_fromUtf8("uOutputUnits"))
        self.horizontalLayout_3.addWidget(self.uOutputUnits)
        self.uArrowBaseSizeLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uArrowBaseSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowBaseSizeLabel.setObjectName(_fromUtf8("uArrowBaseSizeLabel"))
        self.horizontalLayout_3.addWidget(self.uArrowBaseSizeLabel)
        self.uArrowBaseSize = QtGui.QDoubleSpinBox(VectorFieldRendererWidget)
        self.uArrowBaseSize.setObjectName(_fromUtf8("uArrowBaseSize"))
        self.horizontalLayout_3.addWidget(self.uArrowBaseSize)
        self.uBaseBorderColorLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uBaseBorderColorLabel.setObjectName(_fromUtf8("uBaseBorderColorLabel"))
        self.horizontalLayout_3.addWidget(self.uBaseBorderColorLabel)
        self.uBaseBorderColor = gui.QgsColorButton(VectorFieldRendererWidget)
        self.uBaseBorderColor.setObjectName(_fromUtf8("uBaseBorderColor"))
        self.horizontalLayout_3.addWidget(self.uBaseBorderColor)
        self.uBaseColorLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uBaseColorLabel.setObjectName(_fromUtf8("uBaseColorLabel"))
        self.horizontalLayout_3.addWidget(self.uBaseColorLabel)
        self.uFillBase = QtGui.QCheckBox(VectorFieldRendererWidget)
        self.uFillBase.setText(_fromUtf8(""))
        self.uFillBase.setObjectName(_fromUtf8("uFillBase"))
        self.horizontalLayout_3.addWidget(self.uFillBase)
        self.uBaseColor = gui.QgsColorButton(VectorFieldRendererWidget)
        self.uBaseColor.setObjectName(_fromUtf8("uBaseColor"))
        self.horizontalLayout_3.addWidget(self.uBaseColor)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.uArrowScaleLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uArrowScaleLabel.setObjectName(_fromUtf8("uArrowScaleLabel"))
        self.horizontalLayout_4.addWidget(self.uArrowScaleLabel)
        self.uArrowScale = QtGui.QLineEdit(VectorFieldRendererWidget)
        self.uArrowScale.setObjectName(_fromUtf8("uArrowScale"))
        self.horizontalLayout_4.addWidget(self.uArrowScale)
        self.uScaleUnits = QtGui.QPushButton(VectorFieldRendererWidget)
        self.uScaleUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uScaleUnits.setObjectName(_fromUtf8("uScaleUnits"))
        self.horizontalLayout_4.addWidget(self.uScaleUnits)
        self.uScaleGroupLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uScaleGroupLabel.setObjectName(_fromUtf8("uScaleGroupLabel"))
        self.horizontalLayout_4.addWidget(self.uScaleGroupLabel)
        self.uScaleGroup = QtGui.QLineEdit(VectorFieldRendererWidget)
        self.uScaleGroup.setObjectName(_fromUtf8("uScaleGroup"))
        self.horizontalLayout_4.addWidget(self.uScaleGroup)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uLegendTextLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uLegendTextLabel.setObjectName(_fromUtf8("uLegendTextLabel"))
        self.horizontalLayout.addWidget(self.uLegendTextLabel)
        self.uLegendText = QtGui.QLineEdit(VectorFieldRendererWidget)
        self.uLegendText.setObjectName(_fromUtf8("uLegendText"))
        self.horizontalLayout.addWidget(self.uLegendText)
        self.uScaleBoxTextLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uScaleBoxTextLabel.setObjectName(_fromUtf8("uScaleBoxTextLabel"))
        self.horizontalLayout.addWidget(self.uScaleBoxTextLabel)
        self.uScaleBoxText = QtGui.QLineEdit(VectorFieldRendererWidget)
        self.uScaleBoxText.setObjectName(_fromUtf8("uScaleBoxText"))
        self.horizontalLayout.addWidget(self.uScaleBoxText)
        self.uShowScaleBoxLabel = QtGui.QLabel(VectorFieldRendererWidget)
        self.uShowScaleBoxLabel.setObjectName(_fromUtf8("uShowScaleBoxLabel"))
        self.horizontalLayout.addWidget(self.uShowScaleBoxLabel)
        self.uShowInScaleBox = QtGui.QCheckBox(VectorFieldRendererWidget)
        self.uShowInScaleBox.setText(_fromUtf8(""))
        self.uShowInScaleBox.setObjectName(_fromUtf8("uShowInScaleBox"))
        self.horizontalLayout.addWidget(self.uShowInScaleBox)
        self.uHelpButton = QtGui.QPushButton(VectorFieldRendererWidget)
        self.uHelpButton.setObjectName(_fromUtf8("uHelpButton"))
        self.horizontalLayout.addWidget(self.uHelpButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.uXFieldLabel.setBuddy(self.uXField)
        self.uYFieldLabel.setBuddy(self.uYField)
        self.uArrowHeadSizeLabel.setBuddy(self.uArrowHeadSize)
        self.uArrowHeadMaxSizeLabel.setBuddy(self.uArrowHeadMaxSize)
        self.uArrowWidthLabel.setBuddy(self.uArrowWidth)
        self.uArrowColorLabel.setBuddy(self.uArrowColor)
        self.uCxxFieldLabel.setBuddy(self.uCxxField)
        self.uCxyFieldLabel.setBuddy(self.uCxyField)
        self.uEllipseScaleLabel.setBuddy(self.uEllipseScale)
        self.uCyyFieldLabel.setBuddy(self.uCyyField)
        self.uEllipseWidthLabel.setBuddy(self.uEllipseBorderWidth)
        self.uDrawEllipseLabel.setBuddy(self.uFillEllipse)
        self.uEllipseColorLayoutLabel.setBuddy(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel.setBuddy(self.uEllipseFillColor)
        self.uOutputUnitLabel.setBuddy(self.uOutputUnits)
        self.uArrowBaseSizeLabel.setBuddy(self.uArrowBaseSize)
        self.uBaseBorderColorLabel.setBuddy(self.uBaseBorderColor)
        self.uBaseColorLabel.setBuddy(self.uBaseColor)
        self.uArrowScaleLabel.setBuddy(self.uArrowScale)
        self.uScaleGroupLabel.setBuddy(self.uScaleGroup)
        self.uLegendTextLabel.setBuddy(self.uLegendText)
        self.uScaleBoxTextLabel.setBuddy(self.uScaleBoxText)
        self.uShowScaleBoxLabel.setBuddy(self.uShowInScaleBox)

        self.retranslateUi(VectorFieldRendererWidget)
        self.uTabManager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VectorFieldRendererWidget)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypeCartesian, self.uFieldTypePolar)
        VectorFieldRendererWidget.setTabOrder(self.uFieldTypePolar, self.uAngleOrientationEast)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationEast, self.uAngleOrientationNorth)
        VectorFieldRendererWidget.setTabOrder(self.uAngleOrientationNorth, self.uAngleUnitsDegrees)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsDegrees, self.uAngleUnitsRadians)
        VectorFieldRendererWidget.setTabOrder(self.uAngleUnitsRadians, self.uArrowHeadMaxSize)

    def retranslateUi(self, VectorFieldRendererWidget):
        VectorFieldRendererWidget.setWindowTitle(_translate("VectorFieldRendererWidget", "Form", None))
        self.uCrashWarning.setText(_translate("VectorFieldRendererWidget", "Warning: Do not select another type of renderer above: QGIS will crash!", None))
        self.uVectorFieldTypeGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Vector field type", None))
        self.uFieldTypeCartesian.setText(_translate("VectorFieldRendererWidget", "Cartesian (XY) field", None))
        self.uFieldTypePolar.setText(_translate("VectorFieldRendererWidget", "Polar (length,angle) field", None))
        self.uFieldTypeHeight.setText(_translate("VectorFieldRendererWidget", "Height only", None))
        self.uFieldTypeNone.setText(_translate("VectorFieldRendererWidget", "None", None))
        self.uXFieldLabel.setText(_translate("VectorFieldRendererWidget", "X attribute", None))
        self.uYFieldLabel.setText(_translate("VectorFieldRendererWidget", "Y attribute", None))
        self.uYField.setToolTip(_translate("VectorFieldRendererWidget", "Select the y/angle field", None))
        self.uXField.setToolTip(_translate("VectorFieldRendererWidget", "Select the X/length field", None))
        self.uOrientationGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle orientation", None))
        self.uAngleOrientationEast.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation", None))
        self.uAngleOrientationEast.setText(_translate("VectorFieldRendererWidget", "North from east", None))
        self.uAngleOrientationNorth.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation", None))
        self.uAngleOrientationNorth.setText(_translate("VectorFieldRendererWidget", "East from north", None))
        self.uAngleUnitsGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle units", None))
        self.uAngleUnitsDegrees.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units", None))
        self.uAngleUnitsDegrees.setText(_translate("VectorFieldRendererWidget", "Degrees", None))
        self.uAngleUnitsRadians.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units", None))
        self.uAngleUnitsRadians.setText(_translate("VectorFieldRendererWidget", "Radians", None))
        self.uArrowFormatGroup.setTitle(_translate("VectorFieldRendererWidget", "Arrow format", None))
        self.uArrowHeadSizeLabel.setText(_translate("VectorFieldRendererWidget", "Size: Head (relative)", None))
        self.uArrowHeadSize.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length", None))
        self.uArrowHeadMaxSizeLabel.setText(_translate("VectorFieldRendererWidget", "Head (max)", None))
        self.uArrowHeadMaxSize.setToolTip(_translate("VectorFieldRendererWidget", "Maximum arrow head size", None))
        self.uHeadWidthLabel.setText(_translate("VectorFieldRendererWidget", "Head border width", None))
        self.uHeadWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft", None))
        self.uArrowWidthLabel.setText(_translate("VectorFieldRendererWidget", " Shaft width", None))
        self.uArrowWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft", None))
        self.uArrowColorLabel.setText(_translate("VectorFieldRendererWidget", "Colour: Head border/shaft", None))
        self.uArrowColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour", None))
        self.uArrowColor.setText(_translate("VectorFieldRendererWidget", "change", None))
        self.uArrowHeadColorLabel.setText(_translate("VectorFieldRendererWidget", "Head fill?", None))
        self.uArrowHeadColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour", None))
        self.uArrowHeadColor.setText(_translate("VectorFieldRendererWidget", "change", None))
        self.uArrowHeadShapeFrontLabel.setText(_translate("VectorFieldRendererWidget", "Arrow shape (relative x coords): front", None))
        self.uArrowHeadShapeFront.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length", None))
        self.uArrowHeadShapeBackLabel.setText(_translate("VectorFieldRendererWidget", "back outside", None))
        self.uArrowHeadShapeBack.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length", None))
        self.uArrowHeadShapeCentreLabel.setText(_translate("VectorFieldRendererWidget", "back centre", None))
        self.uArrowHeadShapeCentre.setToolTip(_translate("VectorFieldRendererWidget", "Arrow head size as a multiple of the length", None))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uVectorTab), _translate("VectorFieldRendererWidget", "Vector field", None))
        self.uErrorEllipseTypeGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Error ellipse type", None))
        self.uEllipseTypeCovariance.setText(_translate("VectorFieldRendererWidget", "Covariance matrix", None))
        self.uEllipseTypeAxes.setText(_translate("VectorFieldRendererWidget", "Ellipses axes", None))
        self.uEllipseTypeCircular.setText(_translate("VectorFieldRendererWidget", "Circular", None))
        self.uEllipseTypeHeight.setText(_translate("VectorFieldRendererWidget", "Height", None))
        self.uEllipseTypeNone.setText(_translate("VectorFieldRendererWidget", "None", None))
        self.uCxxFieldLabel.setText(_translate("VectorFieldRendererWidget", "Cxx attribute", None))
        self.uCxyFieldLabel.setText(_translate("VectorFieldRendererWidget", "Cxy attribute", None))
        self.uCxyField.setToolTip(_translate("VectorFieldRendererWidget", "Select the y/angle field", None))
        self.uEllipseScaleLabel.setText(_translate("VectorFieldRendererWidget", "Ellipse scale factor", None))
        self.uCxxField.setToolTip(_translate("VectorFieldRendererWidget", "Select the X/length field", None))
        self.uCyyFieldLabel.setText(_translate("VectorFieldRendererWidget", "Cyy attribute", None))
        self.uCyyField.setToolTip(_translate("VectorFieldRendererWidget", "Select the y/angle field", None))
        self.uAxisOrientationGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Ellipse axis orientation", None))
        self.uEllipseOrientationEast.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation", None))
        self.uEllipseOrientationEast.setText(_translate("VectorFieldRendererWidget", "North from east", None))
        self.uEllipseOrientationNorth.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle orientation", None))
        self.uEllipseOrientationNorth.setText(_translate("VectorFieldRendererWidget", "East from north", None))
        self.uAxisAngleUnitsGroupBox.setTitle(_translate("VectorFieldRendererWidget", "Angle units", None))
        self.uEllipseAngleUnitsDegrees.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units", None))
        self.uEllipseAngleUnitsDegrees.setText(_translate("VectorFieldRendererWidget", "Degrees", None))
        self.uEllipseAngleUnitsRadians.setToolTip(_translate("VectorFieldRendererWidget", "Select the angle units", None))
        self.uEllipseAngleUnitsRadians.setText(_translate("VectorFieldRendererWidget", "Radians", None))
        self.uEllipseFormatGroup.setTitle(_translate("VectorFieldRendererWidget", "Ellipse format", None))
        self.uEllipseWidthLabel.setText(_translate("VectorFieldRendererWidget", "Border width", None))
        self.uEllipseBorderWidth.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft", None))
        self.uTickSizeLabel.setText(_translate("VectorFieldRendererWidget", "Tick size ", None))
        self.uEllipseTickSize.setToolTip(_translate("VectorFieldRendererWidget", "Width of the arrow shaft", None))
        self.uDrawEllipseLabel.setText(_translate("VectorFieldRendererWidget", "Draw ellipse", None))
        self.uDrawEllipseAxesLabel.setText(_translate("VectorFieldRendererWidget", "Draw ellipse axes", None))
        self.uEllipseColorLayoutLabel.setText(_translate("VectorFieldRendererWidget", "Colours: Border/axes", None))
        self.uEllipseBorderColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the arrow colour", None))
        self.uEllipseBorderColor.setText(_translate("VectorFieldRendererWidget", "change", None))
        self.uEllipseFillColorLabel.setText(_translate("VectorFieldRendererWidget", "Fill?", None))
        self.uEllipseFillColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base symbol colour", None))
        self.uEllipseFillColor.setText(_translate("VectorFieldRendererWidget", "change", None))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uEllipseTab), _translate("VectorFieldRendererWidget", "Error ellipse", None))
        self.uOutputUnitLabel.setText(_translate("VectorFieldRendererWidget", "Symbol units", None))
        self.uOutputUnits.setText(_translate("VectorFieldRendererWidget", "Millimeter", None))
        self.uArrowBaseSizeLabel.setText(_translate("VectorFieldRendererWidget", "Base size", None))
        self.uArrowBaseSize.setToolTip(_translate("VectorFieldRendererWidget", "Size of the arrow base symbol", None))
        self.uBaseBorderColorLabel.setText(_translate("VectorFieldRendererWidget", "Colours: Border", None))
        self.uBaseBorderColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base border colour", None))
        self.uBaseBorderColor.setText(_translate("VectorFieldRendererWidget", "change", None))
        self.uBaseColorLabel.setText(_translate("VectorFieldRendererWidget", "Fill?", None))
        self.uBaseColor.setToolTip(_translate("VectorFieldRendererWidget", "Change the base symbol colour", None))
        self.uBaseColor.setText(_translate("VectorFieldRendererWidget", "change", None))
        self.uArrowScaleLabel.setText(_translate("VectorFieldRendererWidget", "Scale:  ", None))
        self.uScaleUnits.setText(_translate("VectorFieldRendererWidget", "Millimeter", None))
        self.uScaleGroupLabel.setText(_translate("VectorFieldRendererWidget", "    Scale group", None))
        self.uLegendTextLabel.setText(_translate("VectorFieldRendererWidget", "Legend text", None))
        self.uScaleBoxTextLabel.setText(_translate("VectorFieldRendererWidget", "Scale box text", None))
        self.uShowScaleBoxLabel.setText(_translate("VectorFieldRendererWidget", "Show?", None))
        self.uHelpButton.setText(_translate("VectorFieldRendererWidget", "Help", None))

from qgis import gui
