# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_VectorScaleBoxOptionsDialog.ui'
#
# Created: Wed Apr 24 16:25:36 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VectorScaleBoxOptionsDialog(object):
    def setupUi(self, VectorScaleBoxOptionsDialog):
        VectorScaleBoxOptionsDialog.setObjectName("VectorScaleBoxOptionsDialog")
        VectorScaleBoxOptionsDialog.resize(399, 274)
        self.uMainLayout = QtWidgets.QVBoxLayout(VectorScaleBoxOptionsDialog)
        self.uMainLayout.setObjectName("uMainLayout")
        self.uLocationGroup = QtWidgets.QGroupBox(VectorScaleBoxOptionsDialog)
        self.uLocationGroup.setObjectName("uLocationGroup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.uLocationGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uLocationLayout = QtWidgets.QVBoxLayout()
        self.uLocationLayout.setObjectName("uLocationLayout")
        self.uPositionLayout_2 = QtWidgets.QHBoxLayout()
        self.uPositionLayout_2.setObjectName("uPositionLayout_2")
        self.uPositionLabel = QtWidgets.QLabel(self.uLocationGroup)
        self.uPositionLabel.setObjectName("uPositionLabel")
        self.uPositionLayout_2.addWidget(self.uPositionLabel)
        self.uRadioTL = QtWidgets.QRadioButton(self.uLocationGroup)
        self.uRadioTL.setObjectName("uRadioTL")
        self.uPositionLayout_2.addWidget(self.uRadioTL)
        self.uRadioTR = QtWidgets.QRadioButton(self.uLocationGroup)
        self.uRadioTR.setObjectName("uRadioTR")
        self.uPositionLayout_2.addWidget(self.uRadioTR)
        self.uRadioBL = QtWidgets.QRadioButton(self.uLocationGroup)
        self.uRadioBL.setObjectName("uRadioBL")
        self.uPositionLayout_2.addWidget(self.uRadioBL)
        self.uRadioBR = QtWidgets.QRadioButton(self.uLocationGroup)
        self.uRadioBR.setChecked(True)
        self.uRadioBR.setObjectName("uRadioBR")
        self.uPositionLayout_2.addWidget(self.uRadioBR)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uPositionLayout_2.addItem(spacerItem)
        self.uLocationLayout.addLayout(self.uPositionLayout_2)
        self.verticalLayout_2.addLayout(self.uLocationLayout)
        self.uPositionLayout = QtWidgets.QHBoxLayout()
        self.uPositionLayout.setObjectName("uPositionLayout")
        self.uOffsetXLabel = QtWidgets.QLabel(self.uLocationGroup)
        self.uOffsetXLabel.setObjectName("uOffsetXLabel")
        self.uPositionLayout.addWidget(self.uOffsetXLabel)
        self.uOffsetX = QtWidgets.QSpinBox(self.uLocationGroup)
        self.uOffsetX.setMaximum(300)
        self.uOffsetX.setObjectName("uOffsetX")
        self.uPositionLayout.addWidget(self.uOffsetX)
        self.uOffsetYLabel = QtWidgets.QLabel(self.uLocationGroup)
        self.uOffsetYLabel.setObjectName("uOffsetYLabel")
        self.uPositionLayout.addWidget(self.uOffsetYLabel)
        self.uOffsetY = QtWidgets.QSpinBox(self.uLocationGroup)
        self.uOffsetY.setMaximum(300)
        self.uOffsetY.setObjectName("uOffsetY")
        self.uPositionLayout.addWidget(self.uOffsetY)
        self.uArrowSizeLabel = QtWidgets.QLabel(self.uLocationGroup)
        self.uArrowSizeLabel.setObjectName("uArrowSizeLabel")
        self.uPositionLayout.addWidget(self.uArrowSizeLabel)
        self.uArrowSizePercent = QtWidgets.QSpinBox(self.uLocationGroup)
        self.uArrowSizePercent.setMaximum(30)
        self.uArrowSizePercent.setObjectName("uArrowSizePercent")
        self.uPositionLayout.addWidget(self.uArrowSizePercent)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uPositionLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.uPositionLayout)
        self.uMainLayout.addWidget(self.uLocationGroup)
        self.uBoxGroup = QtWidgets.QGroupBox(VectorScaleBoxOptionsDialog)
        self.uBoxGroup.setObjectName("uBoxGroup")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.uBoxGroup)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.uShowBoxLabel = QtWidgets.QLabel(self.uBoxGroup)
        self.uShowBoxLabel.setObjectName("uShowBoxLabel")
        self.horizontalLayout_6.addWidget(self.uShowBoxLabel)
        self.uShowBox = QtWidgets.QCheckBox(self.uBoxGroup)
        self.uShowBox.setText("")
        self.uShowBox.setObjectName("uShowBox")
        self.horizontalLayout_6.addWidget(self.uShowBox)
        self.uFillBoxLabel = QtWidgets.QLabel(self.uBoxGroup)
        self.uFillBoxLabel.setObjectName("uFillBoxLabel")
        self.horizontalLayout_6.addWidget(self.uFillBoxLabel)
        self.uFillBox = QtWidgets.QCheckBox(self.uBoxGroup)
        self.uFillBox.setText("")
        self.uFillBox.setObjectName("uFillBox")
        self.horizontalLayout_6.addWidget(self.uFillBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.uPenColor = QgsColorButton(self.uBoxGroup)
        self.uPenColor.setObjectName("uPenColor")
        self.horizontalLayout_6.addWidget(self.uPenColor)
        self.uBrushColor = QgsColorButton(self.uBoxGroup)
        self.uBrushColor.setObjectName("uBrushColor")
        self.horizontalLayout_6.addWidget(self.uBrushColor)
        self.uMainLayout.addWidget(self.uBoxGroup)
        self.uTextGroup = QtWidgets.QGroupBox(VectorScaleBoxOptionsDialog)
        self.uTextGroup.setObjectName("uTextGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.uTextGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uTitleLabel = QtWidgets.QLabel(self.uTextGroup)
        self.uTitleLabel.setObjectName("uTitleLabel")
        self.horizontalLayout_3.addWidget(self.uTitleLabel)
        self.uTitle = QtWidgets.QLineEdit(self.uTextGroup)
        self.uTitle.setObjectName("uTitle")
        self.horizontalLayout_3.addWidget(self.uTitle)
        self.uTitleFont = QtWidgets.QPushButton(self.uTextGroup)
        self.uTitleFont.setObjectName("uTitleFont")
        self.horizontalLayout_3.addWidget(self.uTitleFont)
        self.uScaleFont = QtWidgets.QPushButton(self.uTextGroup)
        self.uScaleFont.setObjectName("uScaleFont")
        self.horizontalLayout_3.addWidget(self.uScaleFont)
        self.uMainLayout.addWidget(self.uTextGroup)
        self.uButtonBox = QtWidgets.QDialogButtonBox(VectorScaleBoxOptionsDialog)
        self.uButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.uButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.uButtonBox.setObjectName("uButtonBox")
        self.uMainLayout.addWidget(self.uButtonBox)
        self.uPositionLabel.setBuddy(self.uRadioTL)
        self.uOffsetXLabel.setBuddy(self.uOffsetX)
        self.uOffsetYLabel.setBuddy(self.uOffsetY)
        self.uArrowSizeLabel.setBuddy(self.uArrowSizePercent)
        self.uShowBoxLabel.setBuddy(self.uShowBox)
        self.uFillBoxLabel.setBuddy(self.uFillBox)
        self.uTitleLabel.setBuddy(self.uTitle)

        self.retranslateUi(VectorScaleBoxOptionsDialog)
        self.uButtonBox.accepted.connect(VectorScaleBoxOptionsDialog.accept)
        self.uButtonBox.rejected.connect(VectorScaleBoxOptionsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(VectorScaleBoxOptionsDialog)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioTL, self.uRadioTR)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioTR, self.uRadioBL)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioBL, self.uRadioBR)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uRadioBR, self.uOffsetX)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uOffsetX, self.uOffsetY)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uOffsetY, self.uArrowSizePercent)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uArrowSizePercent, self.uShowBox)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uShowBox, self.uFillBox)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uFillBox, self.uPenColor)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uPenColor, self.uBrushColor)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uBrushColor, self.uTitle)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uTitle, self.uTitleFont)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uTitleFont, self.uScaleFont)
        VectorScaleBoxOptionsDialog.setTabOrder(self.uScaleFont, self.uButtonBox)

    def retranslateUi(self, VectorScaleBoxOptionsDialog):
        VectorScaleBoxOptionsDialog.setWindowTitle(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Vector scale box options", None))
        self.uLocationGroup.setTitle(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Location", None))
        self.uPositionLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Position:", None))
        self.uRadioTL.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Top left", None))
        self.uRadioTR.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Top right", None))
        self.uRadioBL.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Bottom left", None))
        self.uRadioBR.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Bottom right", None))
        self.uOffsetXLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Offset: X", None))
        self.uOffsetYLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "   Y", None))
        self.uArrowSizeLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "     Approx arrow size (%)", None))
        self.uBoxGroup.setTitle(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Box", None))
        self.uShowBoxLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Draw box?", None))
        self.uFillBoxLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Fill box?", None))
        self.uPenColor.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Border color", None))
        self.uBrushColor.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Fill color", None))
        self.uTextGroup.setTitle(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Text", None))
        self.uTitleLabel.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Title: ", None))
        self.uTitleFont.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Title font", None))
        self.uScaleFont.setText(QtCore.QCoreApplication.translate("VectorScaleBoxOptionsDialog", "Scale font", None))

from qgis.gui import QgsColorButton
