# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ccrook/projects/qgis/plugins/qgis3/VectorFieldRenderer/VectorFieldLayerManager/Ui_VectorFieldLayerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_VectorFieldLayerWidget(object):
    def setupUi(self, VectorFieldLayerWidget):
        VectorFieldLayerWidget.setObjectName("VectorFieldLayerWidget")
        VectorFieldLayerWidget.resize(791, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VectorFieldLayerWidget.sizePolicy().hasHeightForWidth())
        VectorFieldLayerWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(VectorFieldLayerWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.uLayerName = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uLayerName.setObjectName("uLayerName")
        self.verticalLayout_4.addWidget(self.uLayerName)
        self.uTabManager = QtWidgets.QTabWidget(VectorFieldLayerWidget)
        self.uTabManager.setObjectName("uTabManager")
        self.uVectorTab = QtWidgets.QWidget()
        self.uVectorTab.setObjectName("uVectorTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.uVectorTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.uVectorFieldTypeGroupBox = QtWidgets.QGroupBox(self.uVectorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uVectorFieldTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uVectorFieldTypeGroupBox.setSizePolicy(sizePolicy)
        self.uVectorFieldTypeGroupBox.setObjectName("uVectorFieldTypeGroupBox")
        self.uFieldTypeLayout = QtWidgets.QHBoxLayout(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeLayout.setContentsMargins(0, 0, 0, 0)
        self.uFieldTypeLayout.setSpacing(15)
        self.uFieldTypeLayout.setObjectName("uFieldTypeLayout")
        self.uFieldTypeCartesian = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeCartesian.setChecked(True)
        self.uFieldTypeCartesian.setObjectName("uFieldTypeCartesian")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeCartesian)
        self.uFieldTypePolar = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypePolar.setObjectName("uFieldTypePolar")
        self.uFieldTypeLayout.addWidget(self.uFieldTypePolar)
        self.uFieldTypeHeight = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeHeight.setObjectName("uFieldTypeHeight")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeHeight)
        self.uFieldTypeNone = QtWidgets.QRadioButton(self.uVectorFieldTypeGroupBox)
        self.uFieldTypeNone.setObjectName("uFieldTypeNone")
        self.uFieldTypeLayout.addWidget(self.uFieldTypeNone)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uFieldTypeLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.uVectorFieldTypeGroupBox)
        self.uVectorFieldGrid = QtWidgets.QGridLayout()
        self.uVectorFieldGrid.setObjectName("uVectorFieldGrid")
        self.uXFieldLabel = QtWidgets.QLabel(self.uVectorTab)
        self.uXFieldLabel.setObjectName("uXFieldLabel")
        self.uVectorFieldGrid.addWidget(self.uXFieldLabel, 0, 0, 1, 1)
        self.uYFieldLabel = QtWidgets.QLabel(self.uVectorTab)
        self.uYFieldLabel.setObjectName("uYFieldLabel")
        self.uVectorFieldGrid.addWidget(self.uYFieldLabel, 1, 0, 1, 1)
        self.uXField = gui.QgsFieldComboBox(self.uVectorTab)
        self.uXField.setObjectName("uXField")
        self.uVectorFieldGrid.addWidget(self.uXField, 0, 1, 1, 1)
        self.uYField = gui.QgsFieldComboBox(self.uVectorTab)
        self.uYField.setObjectName("uYField")
        self.uVectorFieldGrid.addWidget(self.uYField, 1, 1, 1, 1)
        self.uVectorFieldGrid.setColumnStretch(1, 1)
        self.verticalLayout.addLayout(self.uVectorFieldGrid)
        self.uAngleFormatLayout = QtWidgets.QHBoxLayout()
        self.uAngleFormatLayout.setContentsMargins(0, -1, 0, -1)
        self.uAngleFormatLayout.setObjectName("uAngleFormatLayout")
        self.uOrientationGroupBox = QtWidgets.QGroupBox(self.uVectorTab)
        self.uOrientationGroupBox.setEnabled(True)
        self.uOrientationGroupBox.setObjectName("uOrientationGroupBox")
        self.uOrientationLayout = QtWidgets.QHBoxLayout(self.uOrientationGroupBox)
        self.uOrientationLayout.setContentsMargins(0, 0, 0, 0)
        self.uOrientationLayout.setSpacing(15)
        self.uOrientationLayout.setObjectName("uOrientationLayout")
        self.uAngleOrientationEast = QtWidgets.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationEast.setChecked(True)
        self.uAngleOrientationEast.setObjectName("uAngleOrientationEast")
        self.uOrientationLayout.addWidget(self.uAngleOrientationEast)
        self.uAngleOrientationNorth = QtWidgets.QRadioButton(self.uOrientationGroupBox)
        self.uAngleOrientationNorth.setObjectName("uAngleOrientationNorth")
        self.uOrientationLayout.addWidget(self.uAngleOrientationNorth)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uOrientationLayout.addItem(spacerItem1)
        self.uAngleFormatLayout.addWidget(self.uOrientationGroupBox)
        self.uAngleUnitsGroupBox = QtWidgets.QGroupBox(self.uVectorTab)
        self.uAngleUnitsGroupBox.setEnabled(True)
        self.uAngleUnitsGroupBox.setObjectName("uAngleUnitsGroupBox")
        self.uAngleUnitsLayout = QtWidgets.QHBoxLayout(self.uAngleUnitsGroupBox)
        self.uAngleUnitsLayout.setContentsMargins(0, 0, 0, 0)
        self.uAngleUnitsLayout.setSpacing(15)
        self.uAngleUnitsLayout.setObjectName("uAngleUnitsLayout")
        self.uAngleUnitsDegrees = QtWidgets.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsDegrees.setChecked(True)
        self.uAngleUnitsDegrees.setObjectName("uAngleUnitsDegrees")
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsDegrees)
        self.uAngleUnitsRadians = QtWidgets.QRadioButton(self.uAngleUnitsGroupBox)
        self.uAngleUnitsRadians.setEnabled(True)
        self.uAngleUnitsRadians.setObjectName("uAngleUnitsRadians")
        self.uAngleUnitsLayout.addWidget(self.uAngleUnitsRadians)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uAngleUnitsLayout.addItem(spacerItem2)
        self.uAngleFormatLayout.addWidget(self.uAngleUnitsGroupBox)
        self.verticalLayout.addLayout(self.uAngleFormatLayout)
        self.uArrowFormatGroup = QtWidgets.QGroupBox(self.uVectorTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uArrowFormatGroup.sizePolicy().hasHeightForWidth())
        self.uArrowFormatGroup.setSizePolicy(sizePolicy)
        self.uArrowFormatGroup.setObjectName("uArrowFormatGroup")
        self.uArrowFormatLayout = QtWidgets.QVBoxLayout(self.uArrowFormatGroup)
        self.uArrowFormatLayout.setContentsMargins(0, 0, 0, 0)
        self.uArrowFormatLayout.setObjectName("uArrowFormatLayout")
        self.uArrowFormatSizeLayout = QtWidgets.QHBoxLayout()
        self.uArrowFormatSizeLayout.setObjectName("uArrowFormatSizeLayout")
        self.uArrowHeadWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowHeadWidthLabel.setObjectName("uArrowHeadWidthLabel")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowHeadWidthLabel)
        self.uArrowHeadWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadWidth.setObjectName("uArrowHeadWidth")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowHeadWidth)
        self.uArrowShaftWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowShaftWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowShaftWidthLabel.setObjectName("uArrowShaftWidthLabel")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowShaftWidthLabel)
        self.uArrowShaftWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowShaftWidth.setObjectName("uArrowShaftWidth")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowShaftWidth)
        self.uArrowHeadRelativeLengthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowHeadRelativeLengthLabel.setObjectName("uArrowHeadRelativeLengthLabel")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowHeadRelativeLengthLabel)
        self.uArrowHeadRelativeLength = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowHeadRelativeLength.setMinimum(0.0)
        self.uArrowHeadRelativeLength.setMaximum(10.0)
        self.uArrowHeadRelativeLength.setSingleStep(0.5)
        self.uArrowHeadRelativeLength.setObjectName("uArrowHeadRelativeLength")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowHeadRelativeLength)
        self.uArrowMaxRelativeHeadSizeLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowMaxRelativeHeadSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowMaxRelativeHeadSizeLabel.setObjectName("uArrowMaxRelativeHeadSizeLabel")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowMaxRelativeHeadSizeLabel)
        self.uArrowMaxRelativeHeadSize = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowMaxRelativeHeadSize.setMinimum(0.0)
        self.uArrowMaxRelativeHeadSize.setMaximum(2.0)
        self.uArrowMaxRelativeHeadSize.setSingleStep(0.1)
        self.uArrowMaxRelativeHeadSize.setObjectName("uArrowMaxRelativeHeadSize")
        self.uArrowFormatSizeLayout.addWidget(self.uArrowMaxRelativeHeadSize)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowFormatSizeLayout.addItem(spacerItem3)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatSizeLayout)
        self.uArrowFormatColourLayout = QtWidgets.QHBoxLayout()
        self.uArrowFormatColourLayout.setObjectName("uArrowFormatColourLayout")
        self.uArrowBorderWidthLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uArrowBorderWidthLabel.setObjectName("uArrowBorderWidthLabel")
        self.uArrowFormatColourLayout.addWidget(self.uArrowBorderWidthLabel)
        self.uArrowBorderWidth = QtWidgets.QDoubleSpinBox(self.uArrowFormatGroup)
        self.uArrowBorderWidth.setObjectName("uArrowBorderWidth")
        self.uArrowFormatColourLayout.addWidget(self.uArrowBorderWidth)
        self.uArrowBorderColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowBorderColor.setAllowOpacity(True)
        self.uArrowBorderColor.setObjectName("uArrowBorderColor")
        self.uArrowFormatColourLayout.addWidget(self.uArrowBorderColor)
        self.uFillArrowLabel = QtWidgets.QLabel(self.uArrowFormatGroup)
        self.uFillArrowLabel.setObjectName("uFillArrowLabel")
        self.uArrowFormatColourLayout.addWidget(self.uFillArrowLabel)
        self.uFillArrow = QtWidgets.QCheckBox(self.uArrowFormatGroup)
        self.uFillArrow.setText("")
        self.uFillArrow.setObjectName("uFillArrow")
        self.uArrowFormatColourLayout.addWidget(self.uFillArrow)
        self.uArrowFillColor = gui.QgsColorButton(self.uArrowFormatGroup)
        self.uArrowFillColor.setAllowOpacity(True)
        self.uArrowFillColor.setObjectName("uArrowFillColor")
        self.uArrowFormatColourLayout.addWidget(self.uArrowFillColor)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowFormatColourLayout.addItem(spacerItem4)
        self.uArrowFormatLayout.addLayout(self.uArrowFormatColourLayout)
        self.verticalLayout.addWidget(self.uArrowFormatGroup)
        self.uVectorFieldAlignmentFrame = QtWidgets.QFrame(self.uVectorTab)
        self.uVectorFieldAlignmentFrame.setObjectName("uVectorFieldAlignmentFrame")
        self.uVectorAlignmentLayout = QtWidgets.QHBoxLayout(self.uVectorFieldAlignmentFrame)
        self.uVectorAlignmentLayout.setContentsMargins(-1, 1, 1, -1)
        self.uVectorAlignmentLayout.setObjectName("uVectorAlignmentLayout")
        self.label_3 = QtWidgets.QLabel(self.uVectorFieldAlignmentFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.uVectorAlignmentLayout.addWidget(self.label_3)
        self.uAlignToMapNorth = QtWidgets.QCheckBox(self.uVectorFieldAlignmentFrame)
        self.uAlignToMapNorth.setText("")
        self.uAlignToMapNorth.setObjectName("uAlignToMapNorth")
        self.uVectorAlignmentLayout.addWidget(self.uAlignToMapNorth)
        self.label_2 = QtWidgets.QLabel(self.uVectorFieldAlignmentFrame)
        self.label_2.setToolTip("")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.uVectorAlignmentLayout.addWidget(self.label_2)
        self.uVectorIsTrueNorth = QtWidgets.QCheckBox(self.uVectorFieldAlignmentFrame)
        self.uVectorIsTrueNorth.setText("")
        self.uVectorIsTrueNorth.setObjectName("uVectorIsTrueNorth")
        self.uVectorAlignmentLayout.addWidget(self.uVectorIsTrueNorth)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uVectorAlignmentLayout.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.uVectorFieldAlignmentFrame)
        self.uTabManager.addTab(self.uVectorTab, "")
        self.uEllipseTab = QtWidgets.QWidget()
        self.uEllipseTab.setObjectName("uEllipseTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.uEllipseTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.uErrorEllipseTypeGroupBox = QtWidgets.QGroupBox(self.uEllipseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uErrorEllipseTypeGroupBox.sizePolicy().hasHeightForWidth())
        self.uErrorEllipseTypeGroupBox.setSizePolicy(sizePolicy)
        self.uErrorEllipseTypeGroupBox.setObjectName("uErrorEllipseTypeGroupBox")
        self.uFieldTypeLayout_2 = QtWidgets.QHBoxLayout(self.uErrorEllipseTypeGroupBox)
        self.uFieldTypeLayout_2.setContentsMargins(0, 0, 0, 0)
        self.uFieldTypeLayout_2.setSpacing(15)
        self.uFieldTypeLayout_2.setObjectName("uFieldTypeLayout_2")
        self.uEllipseTypeCovariance = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCovariance.setChecked(False)
        self.uEllipseTypeCovariance.setObjectName("uEllipseTypeCovariance")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCovariance)
        self.uEllipseTypeAxes = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeAxes.setObjectName("uEllipseTypeAxes")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeAxes)
        self.uEllipseTypeCircular = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeCircular.setObjectName("uEllipseTypeCircular")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeCircular)
        self.uEllipseTypeHeight = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeHeight.setObjectName("uEllipseTypeHeight")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeHeight)
        self.uEllipseTypeNone = QtWidgets.QRadioButton(self.uErrorEllipseTypeGroupBox)
        self.uEllipseTypeNone.setChecked(True)
        self.uEllipseTypeNone.setObjectName("uEllipseTypeNone")
        self.uFieldTypeLayout_2.addWidget(self.uEllipseTypeNone)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uFieldTypeLayout_2.addItem(spacerItem6)
        self.verticalLayout_2.addWidget(self.uErrorEllipseTypeGroupBox)
        self.uVectorFieldGrid_2 = QtWidgets.QGridLayout()
        self.uVectorFieldGrid_2.setObjectName("uVectorFieldGrid_2")
        self.uEmaxFieldLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEmaxFieldLabel.setObjectName("uEmaxFieldLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxFieldLabel, 0, 0, 1, 1)
        self.uEminFieldLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEminFieldLabel.setObjectName("uEminFieldLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEminFieldLabel, 1, 0, 1, 1)
        self.uEllipseScaleLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEllipseScaleLabel.setObjectName("uEllipseScaleLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEllipseScaleLabel, 3, 0, 1, 1)
        self.uArrowScaleLayout_2 = QtWidgets.QHBoxLayout()
        self.uArrowScaleLayout_2.setObjectName("uArrowScaleLayout_2")
        self.uEllipseScale = QtWidgets.QLineEdit(self.uEllipseTab)
        self.uEllipseScale.setObjectName("uEllipseScale")
        self.uArrowScaleLayout_2.addWidget(self.uEllipseScale)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uArrowScaleLayout_2.addItem(spacerItem7)
        self.uVectorFieldGrid_2.addLayout(self.uArrowScaleLayout_2, 3, 2, 1, 1)
        self.uEmaxAzimuthFieldLabel = QtWidgets.QLabel(self.uEllipseTab)
        self.uEmaxAzimuthFieldLabel.setObjectName("uEmaxAzimuthFieldLabel")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxAzimuthFieldLabel, 2, 0, 1, 1)
        self.uEmaxField = gui.QgsFieldComboBox(self.uEllipseTab)
        self.uEmaxField.setObjectName("uEmaxField")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxField, 0, 2, 1, 1)
        self.uEminField = gui.QgsFieldComboBox(self.uEllipseTab)
        self.uEminField.setObjectName("uEminField")
        self.uVectorFieldGrid_2.addWidget(self.uEminField, 1, 2, 1, 1)
        self.uEmaxAzimuthField = gui.QgsFieldComboBox(self.uEllipseTab)
        self.uEmaxAzimuthField.setObjectName("uEmaxAzimuthField")
        self.uVectorFieldGrid_2.addWidget(self.uEmaxAzimuthField, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.uVectorFieldGrid_2)
        self.uAxisAngleFormatLayout = QtWidgets.QHBoxLayout()
        self.uAxisAngleFormatLayout.setContentsMargins(-1, 0, -1, -1)
        self.uAxisAngleFormatLayout.setObjectName("uAxisAngleFormatLayout")
        self.uAxisOrientationGroupBox = QtWidgets.QGroupBox(self.uEllipseTab)
        self.uAxisOrientationGroupBox.setEnabled(True)
        self.uAxisOrientationGroupBox.setObjectName("uAxisOrientationGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.uAxisOrientationGroupBox)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uEllipseOrientationNorth = QtWidgets.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationNorth.setChecked(True)
        self.uEllipseOrientationNorth.setObjectName("uEllipseOrientationNorth")
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationNorth)
        self.uEllipseOrientationEast = QtWidgets.QRadioButton(self.uAxisOrientationGroupBox)
        self.uEllipseOrientationEast.setObjectName("uEllipseOrientationEast")
        self.horizontalLayout_2.addWidget(self.uEllipseOrientationEast)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisOrientationGroupBox)
        self.uAxisAngleUnitsGroupBox = QtWidgets.QGroupBox(self.uEllipseTab)
        self.uAxisAngleUnitsGroupBox.setEnabled(True)
        self.uAxisAngleUnitsGroupBox.setObjectName("uAxisAngleUnitsGroupBox")
        self.uAngleUnitsLayout_2 = QtWidgets.QHBoxLayout(self.uAxisAngleUnitsGroupBox)
        self.uAngleUnitsLayout_2.setContentsMargins(0, 0, 0, 0)
        self.uAngleUnitsLayout_2.setSpacing(15)
        self.uAngleUnitsLayout_2.setObjectName("uAngleUnitsLayout_2")
        self.uEllipseAngleUnitsDegrees = QtWidgets.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsDegrees.setChecked(True)
        self.uEllipseAngleUnitsDegrees.setObjectName("uEllipseAngleUnitsDegrees")
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsDegrees)
        self.uEllipseAngleUnitsRadians = QtWidgets.QRadioButton(self.uAxisAngleUnitsGroupBox)
        self.uEllipseAngleUnitsRadians.setEnabled(True)
        self.uEllipseAngleUnitsRadians.setObjectName("uEllipseAngleUnitsRadians")
        self.uAngleUnitsLayout_2.addWidget(self.uEllipseAngleUnitsRadians)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uAngleUnitsLayout_2.addItem(spacerItem9)
        self.uAxisAngleFormatLayout.addWidget(self.uAxisAngleUnitsGroupBox)
        self.verticalLayout_2.addLayout(self.uAxisAngleFormatLayout)
        self.uEllipseFormatGroup = QtWidgets.QGroupBox(self.uEllipseTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uEllipseFormatGroup.sizePolicy().hasHeightForWidth())
        self.uEllipseFormatGroup.setSizePolicy(sizePolicy)
        self.uEllipseFormatGroup.setObjectName("uEllipseFormatGroup")
        self.uArrowFormatLayout_2 = QtWidgets.QVBoxLayout(self.uEllipseFormatGroup)
        self.uArrowFormatLayout_2.setContentsMargins(0, 0, 0, 0)
        self.uArrowFormatLayout_2.setSpacing(6)
        self.uArrowFormatLayout_2.setObjectName("uArrowFormatLayout_2")
        self.uEllipseFormatLayout1 = QtWidgets.QHBoxLayout()
        self.uEllipseFormatLayout1.setObjectName("uEllipseFormatLayout1")
        self.uDrawEllipse = QtWidgets.QRadioButton(self.uEllipseFormatGroup)
        self.uDrawEllipse.setChecked(True)
        self.uDrawEllipse.setObjectName("uDrawEllipse")
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipse)
        self.uDrawEllipseAxes = QtWidgets.QRadioButton(self.uEllipseFormatGroup)
        self.uDrawEllipseAxes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.uDrawEllipseAxes.setObjectName("uDrawEllipseAxes")
        self.uEllipseFormatLayout1.addWidget(self.uDrawEllipseAxes)
        self.uEllipseWidthLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseWidthLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uEllipseWidthLabel.setObjectName("uEllipseWidthLabel")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseWidthLabel)
        self.uEllipseBorderWidth = QtWidgets.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseBorderWidth.setObjectName("uEllipseBorderWidth")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseBorderWidth)
        self.uEllipseTickSizeLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseTickSizeLabel.setObjectName("uEllipseTickSizeLabel")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseTickSizeLabel)
        self.uEllipseTickSize = QtWidgets.QDoubleSpinBox(self.uEllipseFormatGroup)
        self.uEllipseTickSize.setObjectName("uEllipseTickSize")
        self.uEllipseFormatLayout1.addWidget(self.uEllipseTickSize)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uEllipseFormatLayout1.addItem(spacerItem10)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseFormatLayout1)
        self.uEllipseFormatLayout2 = QtWidgets.QHBoxLayout()
        self.uEllipseFormatLayout2.setContentsMargins(-1, 6, -1, -1)
        self.uEllipseFormatLayout2.setObjectName("uEllipseFormatLayout2")
        self.uEllipseColorLayoutLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseColorLayoutLabel.setObjectName("uEllipseColorLayoutLabel")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseColorLayoutLabel)
        self.uEllipseBorderColor = gui.QgsColorButton(self.uEllipseFormatGroup)
        self.uEllipseBorderColor.setAllowOpacity(True)
        self.uEllipseBorderColor.setObjectName("uEllipseBorderColor")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel = QtWidgets.QLabel(self.uEllipseFormatGroup)
        self.uEllipseFillColorLabel.setObjectName("uEllipseFillColorLabel")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseFillColorLabel)
        self.uFillEllipse = QtWidgets.QCheckBox(self.uEllipseFormatGroup)
        self.uFillEllipse.setText("")
        self.uFillEllipse.setObjectName("uFillEllipse")
        self.uEllipseFormatLayout2.addWidget(self.uFillEllipse)
        self.uEllipseFillColor = gui.QgsColorButton(self.uEllipseFormatGroup)
        self.uEllipseFillColor.setAllowOpacity(True)
        self.uEllipseFillColor.setObjectName("uEllipseFillColor")
        self.uEllipseFormatLayout2.addWidget(self.uEllipseFillColor)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.uEllipseFormatLayout2.addItem(spacerItem11)
        self.uArrowFormatLayout_2.addLayout(self.uEllipseFormatLayout2)
        self.verticalLayout_2.addWidget(self.uEllipseFormatGroup)
        self.uTabManager.addTab(self.uEllipseTab, "")
        self.verticalLayout_4.addWidget(self.uTabManager)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uSymbolUnitsLabel = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uSymbolUnitsLabel.setObjectName("uSymbolUnitsLabel")
        self.horizontalLayout_3.addWidget(self.uSymbolUnitsLabel)
        self.uSymbolUnits = QtWidgets.QPushButton(VectorFieldLayerWidget)
        self.uSymbolUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uSymbolUnits.setObjectName("uSymbolUnits")
        self.horizontalLayout_3.addWidget(self.uSymbolUnits)
        self.uArrowBaseSizeLabel = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uArrowBaseSizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.uArrowBaseSizeLabel.setObjectName("uArrowBaseSizeLabel")
        self.horizontalLayout_3.addWidget(self.uArrowBaseSizeLabel)
        self.uArrowBaseSize = QtWidgets.QDoubleSpinBox(VectorFieldLayerWidget)
        self.uArrowBaseSize.setObjectName("uArrowBaseSize")
        self.horizontalLayout_3.addWidget(self.uArrowBaseSize)
        self.uBaseBorderColorLabel = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uBaseBorderColorLabel.setObjectName("uBaseBorderColorLabel")
        self.horizontalLayout_3.addWidget(self.uBaseBorderColorLabel)
        self.uBaseBorderColor = gui.QgsColorButton(VectorFieldLayerWidget)
        self.uBaseBorderColor.setAllowOpacity(True)
        self.uBaseBorderColor.setObjectName("uBaseBorderColor")
        self.horizontalLayout_3.addWidget(self.uBaseBorderColor)
        self.uBaseColorLabel = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uBaseColorLabel.setObjectName("uBaseColorLabel")
        self.horizontalLayout_3.addWidget(self.uBaseColorLabel)
        self.uFillBase = QtWidgets.QCheckBox(VectorFieldLayerWidget)
        self.uFillBase.setText("")
        self.uFillBase.setObjectName("uFillBase")
        self.horizontalLayout_3.addWidget(self.uFillBase)
        self.uBaseColor = gui.QgsColorButton(VectorFieldLayerWidget)
        self.uBaseColor.setAllowOpacity(True)
        self.uBaseColor.setObjectName("uBaseColor")
        self.horizontalLayout_3.addWidget(self.uBaseColor)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 9, 9, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uArrowScaleLabel = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uArrowScaleLabel.setObjectName("uArrowScaleLabel")
        self.horizontalLayout_4.addWidget(self.uArrowScaleLabel)
        self.uArrowScale = QtWidgets.QLineEdit(VectorFieldLayerWidget)
        self.uArrowScale.setObjectName("uArrowScale")
        self.horizontalLayout_4.addWidget(self.uArrowScale)
        self.uScaleUnits = QtWidgets.QPushButton(VectorFieldLayerWidget)
        self.uScaleUnits.setMinimumSize(QtCore.QSize(100, 0))
        self.uScaleUnits.setObjectName("uScaleUnits")
        self.horizontalLayout_4.addWidget(self.uScaleUnits)
        self.uScaleGroupLabel = QtWidgets.QLabel(VectorFieldLayerWidget)
        self.uScaleGroupLabel.setObjectName("uScaleGroupLabel")
        self.horizontalLayout_4.addWidget(self.uScaleGroupLabel)
        self.uScaleGroup = QtWidgets.QLineEdit(VectorFieldLayerWidget)
        self.uScaleGroup.setObjectName("uScaleGroup")
        self.horizontalLayout_4.addWidget(self.uScaleGroup)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.uVectorLegendFieldsFrame = QtWidgets.QFrame(VectorFieldLayerWidget)
        self.uVectorLegendFieldsFrame.setObjectName("uVectorLegendFieldsFrame")
        self.uVectorLegendFieldsLayout = QtWidgets.QHBoxLayout(self.uVectorLegendFieldsFrame)
        self.uVectorLegendFieldsLayout.setContentsMargins(-1, 1, -1, -1)
        self.uVectorLegendFieldsLayout.setObjectName("uVectorLegendFieldsLayout")
        self.uLegendTextLabel = QtWidgets.QLabel(self.uVectorLegendFieldsFrame)
        self.uLegendTextLabel.setObjectName("uLegendTextLabel")
        self.uVectorLegendFieldsLayout.addWidget(self.uLegendTextLabel)
        self.uLegendText = QtWidgets.QLineEdit(self.uVectorLegendFieldsFrame)
        self.uLegendText.setObjectName("uLegendText")
        self.uVectorLegendFieldsLayout.addWidget(self.uLegendText)
        self.uScaleBoxTextLabel = QtWidgets.QLabel(self.uVectorLegendFieldsFrame)
        self.uScaleBoxTextLabel.setObjectName("uScaleBoxTextLabel")
        self.uVectorLegendFieldsLayout.addWidget(self.uScaleBoxTextLabel)
        self.uScaleBoxText = QtWidgets.QLineEdit(self.uVectorLegendFieldsFrame)
        self.uScaleBoxText.setObjectName("uScaleBoxText")
        self.uVectorLegendFieldsLayout.addWidget(self.uScaleBoxText)
        self.uShowScaleBoxLabel = QtWidgets.QLabel(self.uVectorLegendFieldsFrame)
        self.uShowScaleBoxLabel.setObjectName("uShowScaleBoxLabel")
        self.uVectorLegendFieldsLayout.addWidget(self.uShowScaleBoxLabel)
        self.uShowInScaleBox = QtWidgets.QCheckBox(self.uVectorLegendFieldsFrame)
        self.uShowInScaleBox.setText("")
        self.uShowInScaleBox.setObjectName("uShowInScaleBox")
        self.uVectorLegendFieldsLayout.addWidget(self.uShowInScaleBox)
        self.uHelpButton = QtWidgets.QPushButton(self.uVectorLegendFieldsFrame)
        self.uHelpButton.setObjectName("uHelpButton")
        self.uVectorLegendFieldsLayout.addWidget(self.uHelpButton)
        self.verticalLayout_4.addWidget(self.uVectorLegendFieldsFrame)
        self.uArrowHeadWidthLabel.setBuddy(self.uArrowHeadWidth)
        self.uArrowShaftWidthLabel.setBuddy(self.uArrowShaftWidth)
        self.uArrowMaxRelativeHeadSizeLabel.setBuddy(self.uArrowMaxRelativeHeadSize)
        self.uArrowBorderWidthLabel.setBuddy(self.uArrowBorderWidth)
        self.uFillArrowLabel.setBuddy(self.uFillArrow)
        self.uEllipseScaleLabel.setBuddy(self.uEllipseScale)
        self.uEllipseWidthLabel.setBuddy(self.uEllipseBorderWidth)
        self.uEllipseColorLayoutLabel.setBuddy(self.uEllipseBorderColor)
        self.uEllipseFillColorLabel.setBuddy(self.uEllipseFillColor)
        self.uSymbolUnitsLabel.setBuddy(self.uSymbolUnits)
        self.uArrowBaseSizeLabel.setBuddy(self.uArrowBaseSize)
        self.uBaseBorderColorLabel.setBuddy(self.uBaseBorderColor)
        self.uBaseColorLabel.setBuddy(self.uFillBase)
        self.uArrowScaleLabel.setBuddy(self.uArrowScale)
        self.uScaleGroupLabel.setBuddy(self.uScaleGroup)

        self.retranslateUi(VectorFieldLayerWidget)
        self.uTabManager.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VectorFieldLayerWidget)
        VectorFieldLayerWidget.setTabOrder(self.uTabManager, self.uFieldTypeCartesian)
        VectorFieldLayerWidget.setTabOrder(self.uFieldTypeCartesian, self.uFieldTypePolar)
        VectorFieldLayerWidget.setTabOrder(self.uFieldTypePolar, self.uFieldTypeHeight)
        VectorFieldLayerWidget.setTabOrder(self.uFieldTypeHeight, self.uFieldTypeNone)
        VectorFieldLayerWidget.setTabOrder(self.uFieldTypeNone, self.uXField)
        VectorFieldLayerWidget.setTabOrder(self.uXField, self.uYField)
        VectorFieldLayerWidget.setTabOrder(self.uYField, self.uAngleOrientationNorth)
        VectorFieldLayerWidget.setTabOrder(self.uAngleOrientationNorth, self.uAngleOrientationEast)
        VectorFieldLayerWidget.setTabOrder(self.uAngleOrientationEast, self.uAngleUnitsDegrees)
        VectorFieldLayerWidget.setTabOrder(self.uAngleUnitsDegrees, self.uAngleUnitsRadians)
        VectorFieldLayerWidget.setTabOrder(self.uAngleUnitsRadians, self.uArrowHeadWidth)
        VectorFieldLayerWidget.setTabOrder(self.uArrowHeadWidth, self.uArrowShaftWidth)
        VectorFieldLayerWidget.setTabOrder(self.uArrowShaftWidth, self.uArrowHeadRelativeLength)
        VectorFieldLayerWidget.setTabOrder(self.uArrowHeadRelativeLength, self.uArrowMaxRelativeHeadSize)
        VectorFieldLayerWidget.setTabOrder(self.uArrowMaxRelativeHeadSize, self.uArrowBorderWidth)
        VectorFieldLayerWidget.setTabOrder(self.uArrowBorderWidth, self.uArrowBorderColor)
        VectorFieldLayerWidget.setTabOrder(self.uArrowBorderColor, self.uFillArrow)
        VectorFieldLayerWidget.setTabOrder(self.uFillArrow, self.uArrowFillColor)
        VectorFieldLayerWidget.setTabOrder(self.uArrowFillColor, self.uAlignToMapNorth)
        VectorFieldLayerWidget.setTabOrder(self.uAlignToMapNorth, self.uVectorIsTrueNorth)
        VectorFieldLayerWidget.setTabOrder(self.uVectorIsTrueNorth, self.uEllipseTypeCovariance)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseTypeCovariance, self.uEllipseTypeAxes)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseTypeAxes, self.uEllipseTypeCircular)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseTypeCircular, self.uEllipseTypeHeight)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseTypeHeight, self.uEllipseTypeNone)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseTypeNone, self.uEmaxField)
        VectorFieldLayerWidget.setTabOrder(self.uEmaxField, self.uEminField)
        VectorFieldLayerWidget.setTabOrder(self.uEminField, self.uEmaxAzimuthField)
        VectorFieldLayerWidget.setTabOrder(self.uEmaxAzimuthField, self.uEllipseScale)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseScale, self.uEllipseOrientationNorth)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseOrientationNorth, self.uEllipseOrientationEast)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseOrientationEast, self.uEllipseAngleUnitsDegrees)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseAngleUnitsDegrees, self.uEllipseAngleUnitsRadians)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseAngleUnitsRadians, self.uDrawEllipse)
        VectorFieldLayerWidget.setTabOrder(self.uDrawEllipse, self.uDrawEllipseAxes)
        VectorFieldLayerWidget.setTabOrder(self.uDrawEllipseAxes, self.uEllipseBorderWidth)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseBorderWidth, self.uEllipseTickSize)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseTickSize, self.uEllipseBorderColor)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseBorderColor, self.uFillEllipse)
        VectorFieldLayerWidget.setTabOrder(self.uFillEllipse, self.uEllipseFillColor)
        VectorFieldLayerWidget.setTabOrder(self.uEllipseFillColor, self.uSymbolUnits)
        VectorFieldLayerWidget.setTabOrder(self.uSymbolUnits, self.uArrowBaseSize)
        VectorFieldLayerWidget.setTabOrder(self.uArrowBaseSize, self.uBaseBorderColor)
        VectorFieldLayerWidget.setTabOrder(self.uBaseBorderColor, self.uFillBase)
        VectorFieldLayerWidget.setTabOrder(self.uFillBase, self.uBaseColor)
        VectorFieldLayerWidget.setTabOrder(self.uBaseColor, self.uArrowScale)
        VectorFieldLayerWidget.setTabOrder(self.uArrowScale, self.uScaleUnits)
        VectorFieldLayerWidget.setTabOrder(self.uScaleUnits, self.uScaleGroup)
        VectorFieldLayerWidget.setTabOrder(self.uScaleGroup, self.uLegendText)
        VectorFieldLayerWidget.setTabOrder(self.uLegendText, self.uScaleBoxText)
        VectorFieldLayerWidget.setTabOrder(self.uScaleBoxText, self.uShowInScaleBox)
        VectorFieldLayerWidget.setTabOrder(self.uShowInScaleBox, self.uHelpButton)

    def retranslateUi(self, VectorFieldLayerWidget):
        _translate = QtCore.QCoreApplication.translate
        VectorFieldLayerWidget.setWindowTitle(_translate("VectorFieldLayerWidget", "Form"))
        self.uLayerName.setText(_translate("VectorFieldLayerWidget", "No layer selected"))
        self.uVectorFieldTypeGroupBox.setTitle(_translate("VectorFieldLayerWidget", "Vector field type"))
        self.uFieldTypeCartesian.setText(_translate("VectorFieldLayerWidget", "Cartesian (XY) field"))
        self.uFieldTypePolar.setText(_translate("VectorFieldLayerWidget", "Polar (length,angle) field"))
        self.uFieldTypeHeight.setText(_translate("VectorFieldLayerWidget", "Height only"))
        self.uFieldTypeNone.setText(_translate("VectorFieldLayerWidget", "None"))
        self.uXFieldLabel.setText(_translate("VectorFieldLayerWidget", "X attribute"))
        self.uYFieldLabel.setText(_translate("VectorFieldLayerWidget", "Y attribute"))
        self.uOrientationGroupBox.setTitle(_translate("VectorFieldLayerWidget", "Angle orientation"))
        self.uAngleOrientationEast.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle orientation"))
        self.uAngleOrientationEast.setText(_translate("VectorFieldLayerWidget", "North from east"))
        self.uAngleOrientationNorth.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle orientation"))
        self.uAngleOrientationNorth.setText(_translate("VectorFieldLayerWidget", "East from north"))
        self.uAngleUnitsGroupBox.setTitle(_translate("VectorFieldLayerWidget", "Angle units"))
        self.uAngleUnitsDegrees.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle units"))
        self.uAngleUnitsDegrees.setText(_translate("VectorFieldLayerWidget", "Degrees"))
        self.uAngleUnitsRadians.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle units"))
        self.uAngleUnitsRadians.setText(_translate("VectorFieldLayerWidget", "Radians"))
        self.uArrowFormatGroup.setTitle(_translate("VectorFieldLayerWidget", "Arrow format"))
        self.uArrowHeadWidthLabel.setText(_translate("VectorFieldLayerWidget", "Size: Head"))
        self.uArrowHeadWidth.setToolTip(_translate("VectorFieldLayerWidget", "Maximum arrow head size"))
        self.uArrowShaftWidthLabel.setText(_translate("VectorFieldLayerWidget", " Shaft"))
        self.uArrowShaftWidth.setToolTip(_translate("VectorFieldLayerWidget", "Width of the arrow shaft"))
        self.uArrowHeadRelativeLengthLabel.setText(_translate("VectorFieldLayerWidget", "Relative head length"))
        self.uArrowHeadRelativeLength.setToolTip(_translate("VectorFieldLayerWidget", "Arrow head size as a multiple of the length"))
        self.uArrowMaxRelativeHeadSizeLabel.setText(_translate("VectorFieldLayerWidget", "Max relative head size"))
        self.uArrowMaxRelativeHeadSize.setToolTip(_translate("VectorFieldLayerWidget", "Arrow head size as a multiple of the length"))
        self.uArrowBorderWidthLabel.setText(_translate("VectorFieldLayerWidget", "Style: Border width"))
        self.uArrowBorderWidth.setToolTip(_translate("VectorFieldLayerWidget", "Width of the arrow shaft"))
        self.uArrowBorderColor.setToolTip(_translate("VectorFieldLayerWidget", "Change the arrow colour"))
        self.uArrowBorderColor.setText(_translate("VectorFieldLayerWidget", "change"))
        self.uFillArrowLabel.setText(_translate("VectorFieldLayerWidget", "Fill arrow?"))
        self.uArrowFillColor.setToolTip(_translate("VectorFieldLayerWidget", "Change the arrow colour"))
        self.uArrowFillColor.setText(_translate("VectorFieldLayerWidget", "change"))
        self.label_3.setText(_translate("VectorFieldLayerWidget", "Align vector with map north"))
        self.uAlignToMapNorth.setToolTip(_translate("VectorFieldLayerWidget", "<html><head/><body><p>If selected the vector is drawn in terms of true north on the map, otherwise a north vector is drawn upwards on the map regardless of the map projection or map canvas rotation.  </p></body></html>"))
        self.label_2.setText(_translate("VectorFieldLayerWidget", "Vector defined relative to true north"))
        self.uVectorIsTrueNorth.setToolTip(_translate("VectorFieldLayerWidget", "<html><head/><body><p>If selected the vector is defined in terms of geographic north (true north) even if the layer coordinate reference system is a projection. Otherwise the vector is defined in terms of projection north for layer coordinate systems. Has no effect for geographic layer coordinate systems or for height only vectors.</p></body></html>"))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uVectorTab), _translate("VectorFieldLayerWidget", "Vector field"))
        self.uErrorEllipseTypeGroupBox.setTitle(_translate("VectorFieldLayerWidget", "Error ellipse type"))
        self.uEllipseTypeCovariance.setText(_translate("VectorFieldLayerWidget", "Covariance matrix"))
        self.uEllipseTypeAxes.setText(_translate("VectorFieldLayerWidget", "Ellipses axes"))
        self.uEllipseTypeCircular.setText(_translate("VectorFieldLayerWidget", "Circular"))
        self.uEllipseTypeHeight.setText(_translate("VectorFieldLayerWidget", "Height"))
        self.uEllipseTypeNone.setText(_translate("VectorFieldLayerWidget", "None"))
        self.uEmaxFieldLabel.setText(_translate("VectorFieldLayerWidget", "Major axis error"))
        self.uEminFieldLabel.setText(_translate("VectorFieldLayerWidget", "Minor axis error"))
        self.uEllipseScaleLabel.setText(_translate("VectorFieldLayerWidget", "Ellipse scale factor"))
        self.uEmaxAzimuthFieldLabel.setText(_translate("VectorFieldLayerWidget", "Major axis azimuth"))
        self.uAxisOrientationGroupBox.setTitle(_translate("VectorFieldLayerWidget", "Ellipse axis orientation"))
        self.uEllipseOrientationNorth.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle orientation"))
        self.uEllipseOrientationNorth.setText(_translate("VectorFieldLayerWidget", "North from east"))
        self.uEllipseOrientationEast.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle orientation"))
        self.uEllipseOrientationEast.setText(_translate("VectorFieldLayerWidget", "East from north"))
        self.uAxisAngleUnitsGroupBox.setTitle(_translate("VectorFieldLayerWidget", "Angle units"))
        self.uEllipseAngleUnitsDegrees.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle units"))
        self.uEllipseAngleUnitsDegrees.setText(_translate("VectorFieldLayerWidget", "Degrees"))
        self.uEllipseAngleUnitsRadians.setToolTip(_translate("VectorFieldLayerWidget", "Select the angle units"))
        self.uEllipseAngleUnitsRadians.setText(_translate("VectorFieldLayerWidget", "Radians"))
        self.uEllipseFormatGroup.setTitle(_translate("VectorFieldLayerWidget", "Ellipse format"))
        self.uDrawEllipse.setText(_translate("VectorFieldLayerWidget", "Draw ellipse"))
        self.uDrawEllipseAxes.setText(_translate("VectorFieldLayerWidget", "Draw ellipse axes"))
        self.uEllipseWidthLabel.setText(_translate("VectorFieldLayerWidget", "Border width"))
        self.uEllipseBorderWidth.setToolTip(_translate("VectorFieldLayerWidget", "Width of the arrow shaft"))
        self.uEllipseTickSizeLabel.setText(_translate("VectorFieldLayerWidget", "Tick size "))
        self.uEllipseTickSize.setToolTip(_translate("VectorFieldLayerWidget", "Width of the arrow shaft"))
        self.uEllipseColorLayoutLabel.setText(_translate("VectorFieldLayerWidget", "Colours: Border/axes"))
        self.uEllipseBorderColor.setToolTip(_translate("VectorFieldLayerWidget", "Change the arrow colour"))
        self.uEllipseBorderColor.setText(_translate("VectorFieldLayerWidget", "change"))
        self.uEllipseFillColorLabel.setText(_translate("VectorFieldLayerWidget", "Fill?"))
        self.uEllipseFillColor.setToolTip(_translate("VectorFieldLayerWidget", "Change the base symbol colour"))
        self.uEllipseFillColor.setText(_translate("VectorFieldLayerWidget", "change"))
        self.uTabManager.setTabText(self.uTabManager.indexOf(self.uEllipseTab), _translate("VectorFieldLayerWidget", "Error ellipse"))
        self.uSymbolUnitsLabel.setText(_translate("VectorFieldLayerWidget", "Symbol units"))
        self.uSymbolUnits.setText(_translate("VectorFieldLayerWidget", "Millimeter"))
        self.uArrowBaseSizeLabel.setText(_translate("VectorFieldLayerWidget", "Base size"))
        self.uArrowBaseSize.setToolTip(_translate("VectorFieldLayerWidget", "Size of the arrow base symbol"))
        self.uBaseBorderColorLabel.setText(_translate("VectorFieldLayerWidget", "Colours: Border"))
        self.uBaseBorderColor.setToolTip(_translate("VectorFieldLayerWidget", "Change the base border colour"))
        self.uBaseBorderColor.setText(_translate("VectorFieldLayerWidget", "change"))
        self.uBaseColorLabel.setText(_translate("VectorFieldLayerWidget", "Fill?"))
        self.uBaseColor.setToolTip(_translate("VectorFieldLayerWidget", "Change the base symbol colour"))
        self.uBaseColor.setText(_translate("VectorFieldLayerWidget", "change"))
        self.uArrowScaleLabel.setText(_translate("VectorFieldLayerWidget", "Scale:  "))
        self.uScaleUnits.setText(_translate("VectorFieldLayerWidget", "Millimeter"))
        self.uScaleGroupLabel.setText(_translate("VectorFieldLayerWidget", "    Scale group"))
        self.uLegendTextLabel.setText(_translate("VectorFieldLayerWidget", "Legend text"))
        self.uScaleBoxTextLabel.setText(_translate("VectorFieldLayerWidget", "Scale box text"))
        self.uShowScaleBoxLabel.setText(_translate("VectorFieldLayerWidget", "Show?"))
        self.uHelpButton.setText(_translate("VectorFieldLayerWidget", "Help"))

from qgis import gui
